//! Probe the real C headers for struct sizes and alignments.
//!
//! Several LZ4 types are *caller-allocated*: the original test suite declares
//! `LZ4_stream_t`, `LZ4_streamHC_t`, `LZ4_streamDecode_t` and the xxHash state
//! structs on the stack, then hands us a pointer. Our Rust definitions must
//! therefore match the C layout exactly.
//!
//! We cannot hardcode the numbers, because `LZ4_STREAM_MINSIZE` is
//! `(1UL << LZ4_MEMORY_USAGE) + 32` and tests/Makefile deliberately rebuilds
//! the suite with LZ4_MEMORY_USAGE set to both its MIN and MAX values. So we
//! compile and run a small probe against the actual headers in use and emit
//! the results as Rust constants.

use std::path::PathBuf;
use std::process::Command;

const PROBE: &str = r#"
#define XXH_STATIC_LINKING_ONLY
#define LZ4_STATIC_LINKING_ONLY
#define LZ4_HC_STATIC_LINKING_ONLY
/* LZ4F_CustomMem and the advanced creators live behind this guard
   (lib/lz4frame.h:641). programs/Makefile:146 builds with the matching
   LZ4F_PUBLISH_STATIC_FUNCTIONS, so these are part of the real ABI. */
#define LZ4F_STATIC_LINKING_ONLY
#include <stdio.h>
#include "lz4.h"
#include "lz4hc.h"
#include "lz4frame.h"
#include "xxhash.h"

#define EMIT(name, type) \
    printf("pub const %s_SIZE: usize = %zu;\n", name, sizeof(type)); \
    printf("pub const %s_ALIGN: usize = %zu;\n", name, _Alignof(type));

int main(void) {
    printf("// AUTO-GENERATED by build.rs from the C headers. Do not edit.\n");
    EMIT("LZ4_STREAM",        LZ4_stream_t)
    EMIT("LZ4_STREAMHC",      LZ4_streamHC_t)
    EMIT("LZ4_STREAMDECODE",  LZ4_streamDecode_t)
    EMIT("XXH32_STATE",       XXH32_state_t)
    EMIT("XXH64_STATE",       XXH64_state_t)
    EMIT("LZ4F_PREFERENCES",  LZ4F_preferences_t)
    EMIT("LZ4F_FRAMEINFO",    LZ4F_frameInfo_t)
    EMIT("LZ4F_CCTX_PTR",     LZ4F_cctx*)
    /* Passed BY VALUE across the ABI by LZ4F_create*_advanced(), so a layout
       mismatch here corrupts silently rather than failing to link. */
    EMIT("LZ4F_CUSTOMMEM",    LZ4F_CustomMem)
    EMIT("LZ4F_COMPRESSOPTS",   LZ4F_compressOptions_t)
    EMIT("LZ4F_DECOMPRESSOPTS", LZ4F_decompressOptions_t)
    printf("pub const LZ4_MEMORY_USAGE_PROBED: usize = %d;\n", LZ4_MEMORY_USAGE);
    printf("pub const LZ4_VERSION_NUMBER_PROBED: i32 = %d;\n", LZ4_VERSION_NUMBER);
    return 0;
}
"#;

/// Locate the original lz4 C sources.
///
/// This port lives in its own repository, so the upstream tree is external.
/// Resolution order:
///   1. `$LZ4_SRC` — set this to point anywhere.
///   2. `upstream/` beside this file — where a git submodule would land.
///   3. `../lz4` — a sibling checkout, the common local layout.
fn find_lz4_src(manifest_dir: &std::path::Path) -> PathBuf {
    let candidates: Vec<PathBuf> = match std::env::var_os("LZ4_SRC") {
        Some(p) => vec![PathBuf::from(p)],
        None => vec![
            manifest_dir.join("upstream"),
            manifest_dir.parent().unwrap().join("lz4"),
        ],
    };

    for c in &candidates {
        if c.join("lib").join("lz4.h").is_file() {
            return c.clone();
        }
    }

    panic!(
        "cannot find the lz4 C sources (looked for lib/lz4.h in: {}).\n\
         Set LZ4_SRC to the lz4 checkout, e.g. LZ4_SRC=/path/to/lz4 cargo build",
        candidates
            .iter()
            .map(|p| p.display().to_string())
            .collect::<Vec<_>>()
            .join(", ")
    );
}

fn main() {
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let lz4_src = find_lz4_src(&manifest_dir);
    let lib_dir = lz4_src.join("lib");

    println!("cargo:rerun-if-changed=build.rs");
    for h in ["lz4.h", "lz4hc.h", "lz4frame.h", "xxhash.h"] {
        println!("cargo:rerun-if-changed={}", lib_dir.join(h).display());
    }
    println!("cargo:rerun-if-env-changed=LZ4_MEMORY_USAGE");
    println!("cargo:rerun-if-env-changed=LZ4_SRC");
    // Re-export so the Makefile and any tooling agree on which tree we probed.
    println!("cargo:rustc-env=LZ4_SRC_RESOLVED={}", lz4_src.display());

    let probe_c = out_dir.join("layout_probe.c");
    let probe_bin = out_dir.join("layout_probe");
    std::fs::write(&probe_c, PROBE).expect("write probe source");

    let cc = std::env::var("CC").unwrap_or_else(|_| "cc".into());
    let mut build = Command::new(&cc);
    build
        .arg("-I")
        .arg(&lib_dir)
        .arg(&probe_c)
        .arg("-o")
        .arg(&probe_bin);
    // Honour the same LZ4_MEMORY_USAGE the C suite is being built with.
    if let Ok(mu) = std::env::var("LZ4_MEMORY_USAGE") {
        build.arg(format!("-DLZ4_MEMORY_USAGE={mu}"));
    }

    let status = build.status().expect("failed to invoke C compiler for layout probe");
    assert!(status.success(), "layout probe failed to compile");

    let out = Command::new(&probe_bin).output().expect("run layout probe");
    assert!(out.status.success(), "layout probe failed to run");

    std::fs::write(out_dir.join("layout.rs"), out.stdout).expect("write layout.rs");
}
