// AUTO-GENERATED by port/tools/gen_ffi.py -- do not edit by hand.
//
// One `extern "C"` stub per symbol exported by the original liblz4.a.
// This is the linking skeleton: every name the original C test suite
// asks for exists here, so `fuzzer`/`frametest` link. Bodies are filled
// in module by module.
#![allow(non_snake_case, unused_variables, dead_code)]

use core::ffi::{c_char, c_double, c_float, c_int, c_long, c_longlong,
                c_schar, c_short, c_uchar, c_uint, c_ulong, c_ulonglong,
                c_ushort, c_void};

use crate::types::*;

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_cctx_size(cctx: *const LZ4F_cctx) -> usize {
    unimplemented!("LZ4F_cctx_size")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_compressBegin(cctx: *mut LZ4F_cctx, dstBuffer: *mut c_void, dstCapacity: usize, prefsPtr: *const LZ4F_preferences_t) -> usize {
    unimplemented!("LZ4F_compressBegin")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_compressBegin_usingCDict(cctx: *mut LZ4F_cctx, dstBuffer: *mut c_void, dstCapacity: usize, cdict: *const LZ4F_CDict, prefsPtr: *const LZ4F_preferences_t) -> usize {
    unimplemented!("LZ4F_compressBegin_usingCDict")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_compressBegin_usingDict(cctx: *mut LZ4F_cctx, dstBuffer: *mut c_void, dstCapacity: usize, dictBuffer: *const c_void, dictSize: usize, prefsPtr: *const LZ4F_preferences_t) -> usize {
    unimplemented!("LZ4F_compressBegin_usingDict")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_compressBound(srcSize: usize, prefsPtr: *const LZ4F_preferences_t) -> usize {
    unimplemented!("LZ4F_compressBound")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_compressEnd(cctx: *mut LZ4F_cctx, dstBuffer: *mut c_void, dstCapacity: usize, cOptPtr: *const LZ4F_compressOptions_t) -> usize {
    unimplemented!("LZ4F_compressEnd")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_compressFrame(dstBuffer: *mut c_void, dstCapacity: usize, srcBuffer: *const c_void, srcSize: usize, preferencesPtr: *const LZ4F_preferences_t) -> usize {
    unimplemented!("LZ4F_compressFrame")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_compressFrameBound(srcSize: usize, preferencesPtr: *const LZ4F_preferences_t) -> usize {
    unimplemented!("LZ4F_compressFrameBound")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_compressFrame_usingCDict(cctx: *mut LZ4F_cctx, dst: *mut c_void, dstCapacity: usize, src: *const c_void, srcSize: usize, cdict: *const LZ4F_CDict, preferencesPtr: *const LZ4F_preferences_t) -> usize {
    unimplemented!("LZ4F_compressFrame_usingCDict")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_compressUpdate(cctx: *mut LZ4F_cctx, dstBuffer: *mut c_void, dstCapacity: usize, srcBuffer: *const c_void, srcSize: usize, cOptPtr: *const LZ4F_compressOptions_t) -> usize {
    unimplemented!("LZ4F_compressUpdate")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_compressionLevel_max() -> c_int {
    unimplemented!("LZ4F_compressionLevel_max")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_createCDict(dictBuffer: *const c_void, dictSize: usize) -> *mut LZ4F_CDict {
    unimplemented!("LZ4F_createCDict")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_createCDict_advanced(customMem: LZ4F_CustomMem, dictBuffer: *const c_void, dictSize: usize) -> *mut LZ4F_CDict {
    unimplemented!("LZ4F_createCDict_advanced")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_createCompressionContext(cctxPtr: *mut *mut LZ4F_cctx, version: c_uint) -> LZ4F_errorCode_t {
    unimplemented!("LZ4F_createCompressionContext")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_createCompressionContext_advanced(customMem: LZ4F_CustomMem, version: c_uint) -> *mut LZ4F_cctx {
    unimplemented!("LZ4F_createCompressionContext_advanced")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_createDecompressionContext(dctxPtr: *mut *mut LZ4F_dctx, version: c_uint) -> LZ4F_errorCode_t {
    unimplemented!("LZ4F_createDecompressionContext")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_createDecompressionContext_advanced(customMem: LZ4F_CustomMem, version: c_uint) -> *mut LZ4F_dctx {
    unimplemented!("LZ4F_createDecompressionContext_advanced")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_dctx_size(dctx: *const LZ4F_dctx) -> usize {
    unimplemented!("LZ4F_dctx_size")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_decompress(dctx: *mut LZ4F_dctx, dstBuffer: *mut c_void, dstSizePtr: *mut usize, srcBuffer: *const c_void, srcSizePtr: *mut usize, dOptPtr: *const LZ4F_decompressOptions_t) -> usize {
    unimplemented!("LZ4F_decompress")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_decompress_usingDict(dctxPtr: *mut LZ4F_dctx, dstBuffer: *mut c_void, dstSizePtr: *mut usize, srcBuffer: *const c_void, srcSizePtr: *mut usize, dict: *const c_void, dictSize: usize, decompressOptionsPtr: *const LZ4F_decompressOptions_t) -> usize {
    unimplemented!("LZ4F_decompress_usingDict")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_flush(cctx: *mut LZ4F_cctx, dstBuffer: *mut c_void, dstCapacity: usize, cOptPtr: *const LZ4F_compressOptions_t) -> usize {
    unimplemented!("LZ4F_flush")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_freeCDict(CDict: *mut LZ4F_CDict) {
    unimplemented!("LZ4F_freeCDict")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_freeCompressionContext(cctx: *mut LZ4F_cctx) -> LZ4F_errorCode_t {
    unimplemented!("LZ4F_freeCompressionContext")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_freeDecompressionContext(dctx: *mut LZ4F_dctx) -> LZ4F_errorCode_t {
    unimplemented!("LZ4F_freeDecompressionContext")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_getBlockSize(blockSizeID: LZ4F_blockSizeID_t) -> usize {
    unimplemented!("LZ4F_getBlockSize")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_getErrorCode(functionResult: usize) -> LZ4F_errorCodes {
    unimplemented!("LZ4F_getErrorCode")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_getErrorName(code: LZ4F_errorCode_t) -> *const c_char {
    unimplemented!("LZ4F_getErrorName")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_getFrameInfo(dctx: *mut LZ4F_dctx, frameInfoPtr: *mut LZ4F_frameInfo_t, srcBuffer: *const c_void, srcSizePtr: *mut usize) -> usize {
    unimplemented!("LZ4F_getFrameInfo")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_getVersion() -> c_uint {
    unimplemented!("LZ4F_getVersion")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_headerSize(src: *const c_void, srcSize: usize) -> usize {
    unimplemented!("LZ4F_headerSize")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_isError(code: LZ4F_errorCode_t) -> c_uint {
    unimplemented!("LZ4F_isError")
}

/// from lib/lz4file.h
#[no_mangle]
pub extern "C" fn LZ4F_read(lz4fRead: *mut LZ4_readFile_t, buf: *mut c_void, size: usize) -> usize {
    unimplemented!("LZ4F_read")
}

/// from lib/lz4file.h
#[no_mangle]
pub extern "C" fn LZ4F_readClose(lz4fRead: *mut LZ4_readFile_t) -> LZ4F_errorCode_t {
    unimplemented!("LZ4F_readClose")
}

/// from lib/lz4file.h
#[no_mangle]
pub extern "C" fn LZ4F_readOpen(lz4fRead: *mut *mut LZ4_readFile_t, fp: *mut FILE) -> LZ4F_errorCode_t {
    unimplemented!("LZ4F_readOpen")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_resetDecompressionContext(dctx: *mut LZ4F_dctx) {
    unimplemented!("LZ4F_resetDecompressionContext")
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_uncompressedUpdate(cctx: *mut LZ4F_cctx, dstBuffer: *mut c_void, dstCapacity: usize, srcBuffer: *const c_void, srcSize: usize, cOptPtr: *const LZ4F_compressOptions_t) -> usize {
    unimplemented!("LZ4F_uncompressedUpdate")
}

/// from lib/lz4file.h
#[no_mangle]
pub extern "C" fn LZ4F_write(lz4fWrite: *mut LZ4_writeFile_t, buf: *const c_void, size: usize) -> usize {
    unimplemented!("LZ4F_write")
}

/// from lib/lz4file.h
#[no_mangle]
pub extern "C" fn LZ4F_writeClose(lz4fWrite: *mut LZ4_writeFile_t) -> LZ4F_errorCode_t {
    unimplemented!("LZ4F_writeClose")
}

/// from lib/lz4file.h
#[no_mangle]
pub extern "C" fn LZ4F_writeOpen(lz4fWrite: *mut *mut LZ4_writeFile_t, fp: *mut FILE, prefsPtr: *const LZ4F_preferences_t) -> LZ4F_errorCode_t {
    unimplemented!("LZ4F_writeOpen")
}

/// from lib/xxhash.h
#[no_mangle]
pub extern "C" fn LZ4_XXH32(input: *const c_void, length: usize, seed: c_uint) -> XXH32_hash_t {
    unimplemented!("LZ4_XXH32")
}

/// from lib/xxhash.h
#[no_mangle]
pub extern "C" fn LZ4_XXH32_canonicalFromHash(dst: *mut XXH32_canonical_t, hash: XXH32_hash_t) {
    unimplemented!("LZ4_XXH32_canonicalFromHash")
}

/// from lib/xxhash.h
#[no_mangle]
pub extern "C" fn LZ4_XXH32_copyState(dst_state: *mut XXH32_state_t, src_state: *const XXH32_state_t) {
    unimplemented!("LZ4_XXH32_copyState")
}

/// from lib/xxhash.h
#[no_mangle]
pub extern "C" fn LZ4_XXH32_createState() -> *mut XXH32_state_t {
    unimplemented!("LZ4_XXH32_createState")
}

/// from lib/xxhash.h
#[no_mangle]
pub extern "C" fn LZ4_XXH32_digest(statePtr: *const XXH32_state_t) -> XXH32_hash_t {
    unimplemented!("LZ4_XXH32_digest")
}

/// from lib/xxhash.h
#[no_mangle]
pub extern "C" fn LZ4_XXH32_freeState(statePtr: *mut XXH32_state_t) -> XXH_errorcode {
    unimplemented!("LZ4_XXH32_freeState")
}

/// from lib/xxhash.h
#[no_mangle]
pub extern "C" fn LZ4_XXH32_hashFromCanonical(src: *const XXH32_canonical_t) -> XXH32_hash_t {
    unimplemented!("LZ4_XXH32_hashFromCanonical")
}

/// from lib/xxhash.h
#[no_mangle]
pub extern "C" fn LZ4_XXH32_reset(statePtr: *mut XXH32_state_t, seed: c_uint) -> XXH_errorcode {
    unimplemented!("LZ4_XXH32_reset")
}

/// from lib/xxhash.h
#[no_mangle]
pub extern "C" fn LZ4_XXH32_update(statePtr: *mut XXH32_state_t, input: *const c_void, length: usize) -> XXH_errorcode {
    unimplemented!("LZ4_XXH32_update")
}

/// from lib/xxhash.h
#[no_mangle]
pub extern "C" fn LZ4_XXH64(input: *const c_void, length: usize, seed: c_ulonglong) -> XXH64_hash_t {
    unimplemented!("LZ4_XXH64")
}

/// from lib/xxhash.h
#[no_mangle]
pub extern "C" fn LZ4_XXH64_canonicalFromHash(dst: *mut XXH64_canonical_t, hash: XXH64_hash_t) {
    unimplemented!("LZ4_XXH64_canonicalFromHash")
}

/// from lib/xxhash.h
#[no_mangle]
pub extern "C" fn LZ4_XXH64_copyState(dst_state: *mut XXH64_state_t, src_state: *const XXH64_state_t) {
    unimplemented!("LZ4_XXH64_copyState")
}

/// from lib/xxhash.h
#[no_mangle]
pub extern "C" fn LZ4_XXH64_createState() -> *mut XXH64_state_t {
    unimplemented!("LZ4_XXH64_createState")
}

/// from lib/xxhash.h
#[no_mangle]
pub extern "C" fn LZ4_XXH64_digest(statePtr: *const XXH64_state_t) -> XXH64_hash_t {
    unimplemented!("LZ4_XXH64_digest")
}

/// from lib/xxhash.h
#[no_mangle]
pub extern "C" fn LZ4_XXH64_freeState(statePtr: *mut XXH64_state_t) -> XXH_errorcode {
    unimplemented!("LZ4_XXH64_freeState")
}

/// from lib/xxhash.h
#[no_mangle]
pub extern "C" fn LZ4_XXH64_hashFromCanonical(src: *const XXH64_canonical_t) -> XXH64_hash_t {
    unimplemented!("LZ4_XXH64_hashFromCanonical")
}

/// from lib/xxhash.h
#[no_mangle]
pub extern "C" fn LZ4_XXH64_reset(statePtr: *mut XXH64_state_t, seed: c_ulonglong) -> XXH_errorcode {
    unimplemented!("LZ4_XXH64_reset")
}

/// from lib/xxhash.h
#[no_mangle]
pub extern "C" fn LZ4_XXH64_update(statePtr: *mut XXH64_state_t, input: *const c_void, length: usize) -> XXH_errorcode {
    unimplemented!("LZ4_XXH64_update")
}

/// from lib/xxhash.h
#[no_mangle]
pub extern "C" fn LZ4_XXH_versionNumber() -> c_uint {
    unimplemented!("LZ4_XXH_versionNumber")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_attach_HC_dictionary(working_stream: *mut LZ4_streamHC_t, dictionary_stream: *const LZ4_streamHC_t) {
    unimplemented!("LZ4_attach_HC_dictionary")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_attach_dictionary(workingStream: *mut LZ4_stream_t, dictionaryStream: *const LZ4_stream_t) {
    unimplemented!("LZ4_attach_dictionary")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_compress(src: *const c_char, dest: *mut c_char, srcSize: c_int) -> c_int {
    unimplemented!("LZ4_compress")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_compressBound(inputSize: c_int) -> c_int {
    unimplemented!("LZ4_compressBound")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compressHC(source: *const c_char, dest: *mut c_char, inputSize: c_int) -> c_int {
    unimplemented!("LZ4_compressHC")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compressHC2(source: *const c_char, dest: *mut c_char, inputSize: c_int, compressionLevel: c_int) -> c_int {
    unimplemented!("LZ4_compressHC2")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compressHC2_continue(LZ4HC_Data: *mut c_void, source: *const c_char, dest: *mut c_char, inputSize: c_int, compressionLevel: c_int) -> c_int {
    unimplemented!("LZ4_compressHC2_continue")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compressHC2_limitedOutput(source: *const c_char, dest: *mut c_char, inputSize: c_int, maxOutputSize: c_int, compressionLevel: c_int) -> c_int {
    unimplemented!("LZ4_compressHC2_limitedOutput")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compressHC2_limitedOutput_continue(LZ4HC_Data: *mut c_void, source: *const c_char, dest: *mut c_char, inputSize: c_int, maxOutputSize: c_int, compressionLevel: c_int) -> c_int {
    unimplemented!("LZ4_compressHC2_limitedOutput_continue")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compressHC2_limitedOutput_withStateHC(state: *mut c_void, source: *const c_char, dest: *mut c_char, inputSize: c_int, maxOutputSize: c_int, compressionLevel: c_int) -> c_int {
    unimplemented!("LZ4_compressHC2_limitedOutput_withStateHC")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compressHC2_withStateHC(state: *mut c_void, source: *const c_char, dest: *mut c_char, inputSize: c_int, compressionLevel: c_int) -> c_int {
    unimplemented!("LZ4_compressHC2_withStateHC")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compressHC_continue(LZ4_streamHCPtr: *mut LZ4_streamHC_t, source: *const c_char, dest: *mut c_char, inputSize: c_int) -> c_int {
    unimplemented!("LZ4_compressHC_continue")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compressHC_limitedOutput(source: *const c_char, dest: *mut c_char, inputSize: c_int, maxOutputSize: c_int) -> c_int {
    unimplemented!("LZ4_compressHC_limitedOutput")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compressHC_limitedOutput_continue(LZ4_streamHCPtr: *mut LZ4_streamHC_t, source: *const c_char, dest: *mut c_char, inputSize: c_int, maxOutputSize: c_int) -> c_int {
    unimplemented!("LZ4_compressHC_limitedOutput_continue")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compressHC_limitedOutput_withStateHC(state: *mut c_void, source: *const c_char, dest: *mut c_char, inputSize: c_int, maxOutputSize: c_int) -> c_int {
    unimplemented!("LZ4_compressHC_limitedOutput_withStateHC")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compressHC_withStateHC(state: *mut c_void, source: *const c_char, dest: *mut c_char, inputSize: c_int) -> c_int {
    unimplemented!("LZ4_compressHC_withStateHC")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compress_HC(src: *const c_char, dst: *mut c_char, srcSize: c_int, dstCapacity: c_int, compressionLevel: c_int) -> c_int {
    unimplemented!("LZ4_compress_HC")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compress_HC_continue(streamHCPtr: *mut LZ4_streamHC_t, src: *const c_char, dst: *mut c_char, srcSize: c_int, maxDstSize: c_int) -> c_int {
    unimplemented!("LZ4_compress_HC_continue")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compress_HC_continue_destSize(LZ4_streamHCPtr: *mut LZ4_streamHC_t, src: *const c_char, dst: *mut c_char, srcSizePtr: *mut c_int, targetDstSize: c_int) -> c_int {
    unimplemented!("LZ4_compress_HC_continue_destSize")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compress_HC_destSize(stateHC: *mut c_void, src: *const c_char, dst: *mut c_char, srcSizePtr: *mut c_int, targetDstSize: c_int, compressionLevel: c_int) -> c_int {
    unimplemented!("LZ4_compress_HC_destSize")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compress_HC_extStateHC(stateHC: *mut c_void, src: *const c_char, dst: *mut c_char, srcSize: c_int, maxDstSize: c_int, compressionLevel: c_int) -> c_int {
    unimplemented!("LZ4_compress_HC_extStateHC")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compress_HC_extStateHC_fastReset(state: *mut c_void, src: *const c_char, dst: *mut c_char, srcSize: c_int, dstCapacity: c_int, compressionLevel: c_int) -> c_int {
    unimplemented!("LZ4_compress_HC_extStateHC_fastReset")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_compress_continue(LZ4_streamPtr: *mut LZ4_stream_t, source: *const c_char, dest: *mut c_char, inputSize: c_int) -> c_int {
    unimplemented!("LZ4_compress_continue")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_compress_default(src: *const c_char, dst: *mut c_char, srcSize: c_int, dstCapacity: c_int) -> c_int {
    unimplemented!("LZ4_compress_default")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_compress_destSize(src: *const c_char, dst: *mut c_char, srcSizePtr: *mut c_int, targetDstSize: c_int) -> c_int {
    unimplemented!("LZ4_compress_destSize")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_compress_destSize_extState(state: *mut c_void, src: *const c_char, dst: *mut c_char, srcSizePtr: *mut c_int, targetDstSize: c_int, acceleration: c_int) -> c_int {
    unimplemented!("LZ4_compress_destSize_extState")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_compress_fast(src: *const c_char, dst: *mut c_char, srcSize: c_int, dstCapacity: c_int, acceleration: c_int) -> c_int {
    unimplemented!("LZ4_compress_fast")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_compress_fast_continue(streamPtr: *mut LZ4_stream_t, src: *const c_char, dst: *mut c_char, srcSize: c_int, dstCapacity: c_int, acceleration: c_int) -> c_int {
    unimplemented!("LZ4_compress_fast_continue")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_compress_fast_extState(state: *mut c_void, src: *const c_char, dst: *mut c_char, srcSize: c_int, dstCapacity: c_int, acceleration: c_int) -> c_int {
    unimplemented!("LZ4_compress_fast_extState")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_compress_fast_extState_fastReset(state: *mut c_void, src: *const c_char, dst: *mut c_char, srcSize: c_int, dstCapacity: c_int, acceleration: c_int) -> c_int {
    unimplemented!("LZ4_compress_fast_extState_fastReset")
}

/// from lib/lz4.c
#[no_mangle]
pub extern "C" fn LZ4_compress_forceExtDict(LZ4_dict: *mut LZ4_stream_t, source: *const c_char, dest: *mut c_char, srcSize: c_int) -> c_int {
    unimplemented!("LZ4_compress_forceExtDict")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_compress_limitedOutput(src: *const c_char, dest: *mut c_char, srcSize: c_int, maxOutputSize: c_int) -> c_int {
    unimplemented!("LZ4_compress_limitedOutput")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_compress_limitedOutput_continue(LZ4_streamPtr: *mut LZ4_stream_t, source: *const c_char, dest: *mut c_char, inputSize: c_int, maxOutputSize: c_int) -> c_int {
    unimplemented!("LZ4_compress_limitedOutput_continue")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_compress_limitedOutput_withState(state: *mut c_void, source: *const c_char, dest: *mut c_char, inputSize: c_int, maxOutputSize: c_int) -> c_int {
    unimplemented!("LZ4_compress_limitedOutput_withState")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_compress_withState(state: *mut c_void, source: *const c_char, dest: *mut c_char, inputSize: c_int) -> c_int {
    unimplemented!("LZ4_compress_withState")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_create(inputBuffer: *mut c_char) -> *mut c_void {
    unimplemented!("LZ4_create")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_createHC(inputBuffer: *const c_char) -> *mut c_void {
    unimplemented!("LZ4_createHC")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_createStream() -> *mut LZ4_stream_t {
    unimplemented!("LZ4_createStream")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_createStreamDecode() -> *mut LZ4_streamDecode_t {
    unimplemented!("LZ4_createStreamDecode")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_createStreamHC() -> *mut LZ4_streamHC_t {
    unimplemented!("LZ4_createStreamHC")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_decoderRingBufferSize(maxBlockSize: c_int) -> c_int {
    unimplemented!("LZ4_decoderRingBufferSize")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_decompress_fast(src: *const c_char, dst: *mut c_char, originalSize: c_int) -> c_int {
    unimplemented!("LZ4_decompress_fast")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_decompress_fast_continue(LZ4_streamDecode: *mut LZ4_streamDecode_t, src: *const c_char, dst: *mut c_char, originalSize: c_int) -> c_int {
    unimplemented!("LZ4_decompress_fast_continue")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_decompress_fast_usingDict(src: *const c_char, dst: *mut c_char, originalSize: c_int, dictStart: *const c_char, dictSize: c_int) -> c_int {
    unimplemented!("LZ4_decompress_fast_usingDict")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_decompress_fast_withPrefix64k(src: *const c_char, dst: *mut c_char, originalSize: c_int) -> c_int {
    unimplemented!("LZ4_decompress_fast_withPrefix64k")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_decompress_safe(src: *const c_char, dst: *mut c_char, compressedSize: c_int, dstCapacity: c_int) -> c_int {
    unimplemented!("LZ4_decompress_safe")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_decompress_safe_continue(LZ4_streamDecode: *mut LZ4_streamDecode_t, src: *const c_char, dst: *mut c_char, srcSize: c_int, dstCapacity: c_int) -> c_int {
    unimplemented!("LZ4_decompress_safe_continue")
}

/// from lib/lz4.c
#[no_mangle]
pub extern "C" fn LZ4_decompress_safe_forceExtDict(source: *const c_char, dest: *mut c_char, compressedSize: c_int, maxOutputSize: c_int, dictStart: *const c_void, dictSize: usize) -> c_int {
    unimplemented!("LZ4_decompress_safe_forceExtDict")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_decompress_safe_partial(src: *const c_char, dst: *mut c_char, srcSize: c_int, targetOutputSize: c_int, dstCapacity: c_int) -> c_int {
    unimplemented!("LZ4_decompress_safe_partial")
}

/// from lib/lz4.c
#[no_mangle]
pub extern "C" fn LZ4_decompress_safe_partial_forceExtDict(source: *const c_char, dest: *mut c_char, compressedSize: c_int, targetOutputSize: c_int, dstCapacity: c_int, dictStart: *const c_void, dictSize: usize) -> c_int {
    unimplemented!("LZ4_decompress_safe_partial_forceExtDict")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_decompress_safe_partial_usingDict(src: *const c_char, dst: *mut c_char, compressedSize: c_int, targetOutputSize: c_int, maxOutputSize: c_int, dictStart: *const c_char, dictSize: c_int) -> c_int {
    unimplemented!("LZ4_decompress_safe_partial_usingDict")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_decompress_safe_usingDict(src: *const c_char, dst: *mut c_char, srcSize: c_int, dstCapacity: c_int, dictStart: *const c_char, dictSize: c_int) -> c_int {
    unimplemented!("LZ4_decompress_safe_usingDict")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_decompress_safe_withPrefix64k(src: *const c_char, dst: *mut c_char, compressedSize: c_int, maxDstSize: c_int) -> c_int {
    unimplemented!("LZ4_decompress_safe_withPrefix64k")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_favorDecompressionSpeed(LZ4_streamHCPtr: *mut LZ4_streamHC_t, favor: c_int) {
    unimplemented!("LZ4_favorDecompressionSpeed")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_freeHC(LZ4HC_Data: *mut c_void) -> c_int {
    unimplemented!("LZ4_freeHC")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_freeStream(streamPtr: *mut LZ4_stream_t) -> c_int {
    unimplemented!("LZ4_freeStream")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_freeStreamDecode(LZ4_stream: *mut LZ4_streamDecode_t) -> c_int {
    unimplemented!("LZ4_freeStreamDecode")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_freeStreamHC(streamHCPtr: *mut LZ4_streamHC_t) -> c_int {
    unimplemented!("LZ4_freeStreamHC")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_initStream(stateBuffer: *mut c_void, size: usize) -> *mut LZ4_stream_t {
    unimplemented!("LZ4_initStream")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_initStreamHC(buffer: *mut c_void, size: usize) -> *mut LZ4_streamHC_t {
    unimplemented!("LZ4_initStreamHC")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_loadDict(streamPtr: *mut LZ4_stream_t, dictionary: *const c_char, dictSize: c_int) -> c_int {
    unimplemented!("LZ4_loadDict")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_loadDictHC(streamHCPtr: *mut LZ4_streamHC_t, dictionary: *const c_char, dictSize: c_int) -> c_int {
    unimplemented!("LZ4_loadDictHC")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_loadDictSlow(streamPtr: *mut LZ4_stream_t, dictionary: *const c_char, dictSize: c_int) -> c_int {
    unimplemented!("LZ4_loadDictSlow")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_resetStream(streamPtr: *mut LZ4_stream_t) {
    unimplemented!("LZ4_resetStream")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_resetStreamHC(streamHCPtr: *mut LZ4_streamHC_t, compressionLevel: c_int) {
    unimplemented!("LZ4_resetStreamHC")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_resetStreamHC_fast(streamHCPtr: *mut LZ4_streamHC_t, compressionLevel: c_int) {
    unimplemented!("LZ4_resetStreamHC_fast")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_resetStreamState(state: *mut c_void, inputBuffer: *mut c_char) -> c_int {
    unimplemented!("LZ4_resetStreamState")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_resetStreamStateHC(state: *mut c_void, inputBuffer: *mut c_char) -> c_int {
    unimplemented!("LZ4_resetStreamStateHC")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_resetStream_fast(streamPtr: *mut LZ4_stream_t) {
    unimplemented!("LZ4_resetStream_fast")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_saveDict(streamPtr: *mut LZ4_stream_t, safeBuffer: *mut c_char, maxDictSize: c_int) -> c_int {
    unimplemented!("LZ4_saveDict")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_saveDictHC(streamHCPtr: *mut LZ4_streamHC_t, safeBuffer: *mut c_char, maxDictSize: c_int) -> c_int {
    unimplemented!("LZ4_saveDictHC")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_setCompressionLevel(LZ4_streamHCPtr: *mut LZ4_streamHC_t, compressionLevel: c_int) {
    unimplemented!("LZ4_setCompressionLevel")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_setStreamDecode(LZ4_streamDecode: *mut LZ4_streamDecode_t, dictionary: *const c_char, dictSize: c_int) -> c_int {
    unimplemented!("LZ4_setStreamDecode")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_sizeofState() -> c_int {
    unimplemented!("LZ4_sizeofState")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_sizeofStateHC() -> c_int {
    unimplemented!("LZ4_sizeofStateHC")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_sizeofStreamState() -> c_int {
    unimplemented!("LZ4_sizeofStreamState")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_sizeofStreamStateHC() -> c_int {
    unimplemented!("LZ4_sizeofStreamStateHC")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_slideInputBuffer(state: *mut c_void) -> *mut c_char {
    unimplemented!("LZ4_slideInputBuffer")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_slideInputBufferHC(LZ4HC_Data: *mut c_void) -> *mut c_char {
    unimplemented!("LZ4_slideInputBufferHC")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_uncompress(source: *const c_char, dest: *mut c_char, outputSize: c_int) -> c_int {
    unimplemented!("LZ4_uncompress")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_uncompress_unknownOutputSize(source: *const c_char, dest: *mut c_char, isize: c_int, maxOutputSize: c_int) -> c_int {
    unimplemented!("LZ4_uncompress_unknownOutputSize")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_versionNumber() -> c_int {
    unimplemented!("LZ4_versionNumber")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_versionString() -> *const c_char {
    unimplemented!("LZ4_versionString")
}
