// Originally generated by tools/gen_ffi.py -- NOW EDITED BY HAND.
//
// !! DO NOT RUN `make gen-ffi` !!  It overwrites this file, and as of the
// first implemented function that means destroying work, not regenerating a
// skeleton. It was a bootstrap tool; its job is done.
//
// One `extern "C"` entry point per symbol exported by the original liblz4.a.
// Every name the original C test suite asks for exists here, so
// `fuzzer`/`frametest` link. Bodies are filled in module by module; whatever
// is still `unimplemented!()` panics with its own symbol name.
#![allow(non_snake_case, unused_variables, dead_code, unused_imports)]

use core::ffi::{
    c_char, c_double, c_float, c_int, c_long, c_longlong, c_schar, c_short, c_uchar, c_uint,
    c_ulong, c_ulonglong, c_ushort, c_void,
};

use crate::types::*;

use crate::block::{self, Error as BlockError, Input};
use crate::block::{AbiDecodeState, AbiStreamState};
use core::ops::Range;
use core::slice;

/// Hand the caller's two buffers to `f` in a representation that never aliases.
///
/// `src` and `dst` may point into the **same allocation**: in-place
/// compression (`fuzzer.c:1207-1218`) and decompression (`:1240-1247`) are
/// supported features, not misuse. Holding `&[u8]` and `&mut [u8]` over the
/// same bytes is undefined behaviour, so when the ranges overlap we produce a
/// single slice spanning both, plus indices into it.
///
/// # Safety
///
/// The usual C contract: each pointer is either null with a zero length, or
/// valid for the stated number of bytes. When the ranges overlap they must be
/// part of one allocation, which is what the in-place API contract
/// (`LZ4_COMPRESS_INPLACE_BUFFER_SIZE`, `lz4.h:672-680`) already requires.
unsafe fn with_buffers<R>(
    src: *const c_char,
    src_len: usize,
    dst: *mut c_char,
    dst_len: usize,
    f: impl FnOnce(&mut [u8], Range<usize>, &Input<'_>) -> R,
) -> R {
    let src_addr = src as usize;
    let dst_addr = dst as usize;
    let overlaps = src_len != 0
        && dst_len != 0
        && src_addr < dst_addr.wrapping_add(dst_len)
        && dst_addr < src_addr.wrapping_add(src_len);

    if overlaps {
        let lo = src_addr.min(dst_addr);
        let hi = (src_addr + src_len).max(dst_addr + dst_len);
        let buf = slice::from_raw_parts_mut(lo as *mut u8, hi - lo);
        let s = (src_addr - lo)..(src_addr - lo + src_len);
        let d = (dst_addr - lo)..(dst_addr - lo + dst_len);
        f(buf, d, &Input::Within(s))
    } else {
        // `from_raw_parts` requires non-null even for length 0, and
        // `LZ4_compress_default(NULL, dst, 0, cap)` is a supported call.
        let s: &[u8] = if src.is_null() || src_len == 0 {
            &[]
        } else {
            slice::from_raw_parts(src as *const u8, src_len)
        };
        let d: &mut [u8] = if dst.is_null() || dst_len == 0 {
            &mut []
        } else {
            slice::from_raw_parts_mut(dst as *mut u8, dst_len)
        };
        let range = 0..d.len();
        f(d, range, &Input::Separate(s))
    }
}

#[inline]
fn ranges_overlap(a: usize, a_len: usize, b: usize, b_len: usize) -> bool {
    a_len != 0 && b_len != 0 && a < b.saturating_add(b_len) && b < a.saturating_add(a_len)
}

fn abi_stream_ptr(stream: *mut LZ4_stream_t) -> Option<core::ptr::NonNull<AbiStreamState>> {
    if stream.is_null() || stream as usize % core::mem::align_of::<AbiStreamState>() != 0 {
        None
    } else {
        core::ptr::NonNull::new(stream.cast::<AbiStreamState>())
    }
}

fn abi_decode_ptr(stream: *mut LZ4_streamDecode_t) -> Option<core::ptr::NonNull<AbiDecodeState>> {
    if stream.is_null() || stream as usize % core::mem::align_of::<AbiDecodeState>() != 0 {
        None
    } else {
        core::ptr::NonNull::new(stream.cast::<AbiDecodeState>())
    }
}

unsafe fn compress_ext_state_impl(
    state: *mut c_void,
    src: *const c_char,
    dst: *mut c_char,
    src_size: c_int,
    dst_capacity: c_int,
    acceleration: c_int,
    fast_reset: bool,
) -> c_int {
    if state.is_null()
        || state as usize % core::mem::align_of::<AbiStreamState>() != 0
        || src_size < 0
        || dst_capacity < 0
        || (src_size != 0 && src.is_null())
        || dst.is_null()
        || ranges_overlap(
            state as usize,
            core::mem::size_of::<AbiStreamState>(),
            dst as usize,
            dst_capacity as usize,
        )
    {
        return 0;
    }
    let state_size = core::mem::size_of::<AbiStreamState>();
    let source_snapshot =
        ranges_overlap(state as usize, state_size, src as usize, src_size as usize).then(
            || unsafe { slice::from_raw_parts(src.cast::<u8>(), src_size as usize).to_vec() },
        );
    let state = unsafe { &mut *state.cast::<AbiStreamState>() };
    if let Some(source) = source_snapshot.as_deref() {
        let output = unsafe { slice::from_raw_parts_mut(dst.cast::<u8>(), dst_capacity as usize) };
        return block::compress_abi_ext_state(
            output,
            0..output.len(),
            &Input::Separate(source),
            state,
            acceleration,
            fast_reset,
        )
        .unwrap_or(0) as c_int;
    }
    unsafe {
        with_buffers(
            src,
            src_size as usize,
            dst,
            dst_capacity as usize,
            |buf, range, input| {
                block::compress_abi_ext_state(buf, range, input, state, acceleration, fast_reset)
                    .unwrap_or(0) as c_int
            },
        )
    }
}

#[allow(clippy::too_many_arguments)]
unsafe fn compress_continue_impl(
    stream: *mut LZ4_stream_t,
    src: *const c_char,
    dst: *mut c_char,
    src_size: c_int,
    dst_capacity: c_int,
    acceleration: c_int,
    force_external: bool,
) -> c_int {
    if src_size < 0
        || dst_capacity < 0
        || (src_size != 0 && src.is_null())
        || dst.is_null()
        || stream.is_null()
        || stream as usize % core::mem::align_of::<AbiStreamState>() != 0
    {
        return 0;
    }
    let src_size = src_size as usize;
    let dst_capacity = dst_capacity as usize;
    let context_address = unsafe {
        core::ptr::addr_of!((*stream.cast::<AbiStreamState>()).dict_ctx).read()
    };
    let context = if context_address == 0 {
        None
    } else {
        Some(unsafe { (&*(context_address as *const AbiStreamState)).clone() })
    };
    let state = unsafe { &mut *stream.cast::<AbiStreamState>() };
    state.renormalize(src_size);

    let mut dict_end = state.dictionary.saturating_add(state.dict_size as usize);
    if state.dict_size < 4 && dict_end != src as usize && src_size != 0 && context.is_none() {
        state.dict_size = 0;
        state.dictionary = src as usize;
        dict_end = src as usize;
    }
    let source_end = (src as usize).saturating_add(src_size);
    if source_end > state.dictionary && source_end < dict_end {
        state.dict_size = (dict_end - source_end).min(64 * 1024) as u32;
        if state.dict_size < 4 {
            state.dict_size = 0;
        }
        state.dictionary = dict_end - state.dict_size as usize;
        dict_end = state.dictionary + state.dict_size as usize;
    }

    let prefix = !force_external && dict_end == src as usize;
    let mut context = if prefix { None } else { context };
    if context.is_some() && src_size > 4 * 1024 {
        *state = context.take().unwrap();
    }
    let (dictionary_address, dictionary_size) = if let Some(context) = context.as_ref() {
        (context.dictionary, context.dict_size as usize)
    } else {
        (state.dictionary, state.dict_size as usize)
    };
    let dictionary_snapshot = ranges_overlap(
        dictionary_address,
        dictionary_size,
        dst as usize,
        dst_capacity,
    )
    .then(|| unsafe {
        slice::from_raw_parts(dictionary_address as *const u8, dictionary_size).to_vec()
    });
    let dictionary = dictionary_snapshot.as_deref().unwrap_or_else(|| unsafe {
        slice::from_raw_parts(
            if dictionary_size == 0 {
                core::ptr::NonNull::<u8>::dangling().as_ptr()
            } else {
                dictionary_address as *const u8
            },
            dictionary_size,
        )
    });
    let context_arg = context.as_ref().map(|context| (context, dictionary));
    if context_arg.is_some() {
        state.dict_ctx = 0;
    }
    let result = unsafe {
        with_buffers(src, src_size, dst, dst_capacity, |buf, range, input| {
            block::compress_abi_continue(
                buf,
                range,
                input,
                state,
                dictionary,
                prefix,
                context_arg,
                acceleration,
            )
            .unwrap_or(0)
        })
    };
    if !prefix {
        state.dictionary = src as usize;
        state.dict_size = src_size as u32;
    }
    result as c_int
}

unsafe fn load_dict_impl(
    stream: *mut LZ4_stream_t,
    dictionary: *const c_char,
    dict_size: c_int,
    slow: bool,
) -> c_int {
    let Some(mut state) = abi_stream_ptr(stream) else {
        return 0;
    };
    let state = unsafe { state.as_mut() };
    if dict_size < 0 || (dict_size != 0 && dictionary.is_null()) {
        state.reset();
        return 0;
    }
    let original_size = dict_size as usize;
    let retained_size = original_size.min(64 * 1024);
    let retained = if retained_size == 0 {
        &[]
    } else {
        unsafe {
            slice::from_raw_parts(
                dictionary.cast::<u8>().add(original_size - retained_size),
                retained_size,
            )
        }
    };
    let loaded = state.load_dict(retained, slow);
    if loaded != 0 {
        state.dictionary = dictionary as usize + original_size - loaded;
    }
    loaded as c_int
}

#[allow(clippy::too_many_arguments)]
unsafe fn decompress_safe_histories(
    src: *const c_char,
    dst: *mut c_char,
    compressed_size: c_int,
    output_size: c_int,
    external_address: usize,
    external_size: usize,
    prefix_address: usize,
    prefix_size: usize,
    partial: bool,
) -> c_int {
    if src.is_null()
        || compressed_size < 0
        || output_size < 0
        || (output_size != 0 && dst.is_null())
    {
        return -1;
    }
    let input = unsafe { slice::from_raw_parts(src.cast::<u8>(), compressed_size as usize) };
    let external = if external_size == 0 {
        &[][..]
    } else if external_address == 0 {
        return -1;
    } else {
        unsafe { slice::from_raw_parts(external_address as *const u8, external_size) }
    };
    let prefix = if prefix_size == 0 {
        &[][..]
    } else if prefix_address == 0 {
        return -1;
    } else {
        unsafe { slice::from_raw_parts(prefix_address as *const u8, prefix_size) }
    };
    let mut buffer = vec![0u8; prefix.len() + output_size as usize];
    buffer[..prefix.len()].copy_from_slice(&prefix);
    let start = prefix.len();
    let end = buffer.len();
    let result = decode_result(block::decompress_dict(
        &mut buffer,
        start..end,
        &Input::Separate(input),
        partial,
        output_size as usize,
        external,
        prefix.len(),
    ));
    if result >= 0 && result != 0 {
        unsafe { core::ptr::copy(buffer[start..].as_ptr(), dst.cast::<u8>(), result as usize) };
    }
    result
}

unsafe fn decompress_safe_impl(
    src: *const c_char,
    dst: *mut c_char,
    compressed_size: c_int,
    output_size: c_int,
    dictionary: Option<(*const c_char, usize)>,
    external: bool,
    partial: bool,
) -> c_int {
    let (address, size) = dictionary.map_or((0, 0), |(pointer, size)| (pointer as usize, size));
    let (external_address, external_size, prefix_address, prefix_size) = if external {
        (address, size, 0, 0)
    } else {
        (0, 0, address, size)
    };
    unsafe {
        decompress_safe_histories(
            src,
            dst,
            compressed_size,
            output_size,
            external_address,
            external_size,
            prefix_address,
            prefix_size,
            partial,
        )
    }
}

unsafe fn decompress_safe_continue_impl(
    stream: *mut LZ4_streamDecode_t,
    src: *const c_char,
    dst: *mut c_char,
    compressed_size: c_int,
    output_size: c_int,
) -> c_int {
    let Some(mut state) = abi_decode_ptr(stream) else {
        return -1;
    };
    let state = unsafe { state.as_mut() };
    let contiguous = state.prefix_size != 0 && state.prefix_end == dst as usize;
    if state.prefix_size != 0 && !contiguous {
        state.ext_dict_size = state.prefix_size;
        state.external_dict = state.prefix_end - state.prefix_size;
    }
    let (external_address, external_size, prefix_address, prefix_size) = if state.prefix_size == 0 {
        (0, 0, 0, 0)
    } else if contiguous && state.prefix_size >= 64 * 1024 - 1 {
        let prefix_size = state.prefix_size.min(64 * 1024);
        (0, 0, state.prefix_end - prefix_size, prefix_size)
    } else if contiguous {
        (
            state.external_dict,
            state.ext_dict_size,
            state.prefix_end - state.prefix_size,
            state.prefix_size,
        )
    } else {
        (state.external_dict, state.ext_dict_size, 0, 0)
    };
    let result = unsafe {
        decompress_safe_histories(
            src,
            dst,
            compressed_size,
            output_size,
            external_address,
            external_size,
            prefix_address,
            prefix_size,
            false,
        )
    };
    if result <= 0 {
        return result;
    }
    if state.prefix_size == 0 || !contiguous {
        state.prefix_size = result as usize;
        state.prefix_end = dst as usize + result as usize;
    } else {
        state.prefix_size += result as usize;
        state.prefix_end += result as usize;
    }
    result
}

#[allow(clippy::too_many_arguments)]
unsafe fn decompress_fast_impl(
    src: *const c_char,
    dst: *mut c_char,
    output_size: c_int,
    external_address: usize,
    external_size: usize,
    prefix_address: usize,
    prefix_size: usize,
) -> c_int {
    if src.is_null() || output_size < 0 || (output_size != 0 && dst.is_null()) {
        return -1;
    }
    let external = if external_size == 0 {
        &[][..]
    } else {
        unsafe { slice::from_raw_parts(external_address as *const u8, external_size) }
    };
    let prefix = if prefix_size == 0 {
        &[][..]
    } else {
        unsafe { slice::from_raw_parts(prefix_address as *const u8, prefix_size) }
    };
    let mut output = vec![0u8; output_size as usize];
    match block::decompress_fast_with(
        |index| unsafe { *src.cast::<u8>().add(index) },
        &mut output,
        external,
        prefix,
    ) {
        Ok(consumed) => {
            if !output.is_empty() {
                unsafe { core::ptr::copy(output.as_ptr(), dst.cast::<u8>(), output.len()) };
            }
            consumed as c_int
        }
        Err(_) => -1,
    }
}

unsafe fn decompress_fast_continue_impl(
    stream: *mut LZ4_streamDecode_t,
    src: *const c_char,
    dst: *mut c_char,
    output_size: c_int,
) -> c_int {
    let Some(mut state) = abi_decode_ptr(stream) else {
        return -1;
    };
    let state = unsafe { state.as_mut() };
    let contiguous = state.prefix_size != 0 && state.prefix_end == dst as usize;
    if state.prefix_size != 0 && !contiguous {
        state.ext_dict_size = state.prefix_size;
        state.external_dict = state.prefix_end - state.prefix_size;
    }
    let (external_address, external_size, prefix_address, prefix_size) = if state.prefix_size == 0 {
        (0, 0, 0, 0)
    } else if contiguous {
        (
            state.external_dict,
            state.ext_dict_size,
            state.prefix_end - state.prefix_size,
            state.prefix_size,
        )
    } else {
        (state.external_dict, state.ext_dict_size, 0, 0)
    };
    let result = unsafe {
        decompress_fast_impl(
            src,
            dst,
            output_size,
            external_address,
            external_size,
            prefix_address,
            prefix_size,
        )
    };
    if result <= 0 {
        return result;
    }
    if state.prefix_size == 0 || !contiguous {
        state.prefix_size = output_size as usize;
        state.prefix_end = dst as usize + output_size as usize;
    } else {
        state.prefix_size += output_size as usize;
        state.prefix_end += output_size as usize;
    }
    result
}

/// `Result` in, C integer convention out — done once, per function, because
/// the conventions differ between families (DECISIONS.md §7.1).
#[inline]
fn decode_result(r: Result<usize, BlockError>) -> c_int {
    match r {
        Ok(n) => n as c_int,
        // lz4.c:2462 encodes *where* parsing failed: `-(ip - src) - 1`.
        Err(BlockError::Malformed { consumed }) => -(consumed as c_int) - 1,
        Err(BlockError::OutputTooSmall) => -1,
    }
}

// ===========================================================================
// Frame format (lib/lz4frame.c)
// ===========================================================================
//
// `LZ4F_cctx`/`LZ4F_dctx`/`LZ4F_CDict` are **opaque** to C: it only ever holds
// pointers that came out of our own create functions, so unlike `LZ4_stream_t`
// we choose the layout. Each is a `Box`ed Rust struct, and the handle C carries
// is that `Box`'s raw pointer.
//
// Every entry point in this section returns `size_t`, where an error is
// `(size_t)-(ptrdiff_t)code` — a huge unsigned number, never a negative one.
// `frame::Error::to_code` is the single place that encoding is produced.

use crate::frame::{self, BlockCompressMode, CDict, Cctx, Dctx, FrameInfo, Preferences};

// --- Custom allocators -----------------------------------------------------
//
// `LZ4F_create*_advanced` takes an `LZ4F_CustomMem`: the caller's own
// alloc/calloc/free. `frametest.c:1067-1121` does not merely pass these in, it
// *audits* them — it tracks every live byte the hooks handed out and asserts
// that `LZ4F_cctx_size`/`LZ4F_dctx_size` equal that total, before and after a
// full frame round-trip. So the hooks cannot be accepted and ignored: the
// contexts have to genuinely live in memory the caller allocated.
//
// The state therefore sits in a caller-provided block, with the size recorded
// alongside it so `size_of` can report the same number the hooks recorded, and
// `free` can be called on exactly the pointer that was handed out.

/// A context living in caller-allocated memory.
///
/// `mem` is the `LZ4F_CustomMem` it came from, kept so that `free` uses the
/// matching hook and opaque state — the test asserts on pointer identity, so
/// releasing it through `libc::free` would trip its bookkeeping.
struct Owned<T> {
    /// The block the caller's allocator returned. This *is* the handle C holds.
    block: *mut c_void,
    /// Exactly what was requested from the hook, which is what the test counts.
    size: usize,
    mem: LZ4F_CustomMem,
    value: T,
}

type AllocFn = unsafe extern "C" fn(*mut c_void, usize) -> *mut c_void;
type FreeFn = unsafe extern "C" fn(*mut c_void, *mut c_void);

/// Allocate `Owned<T>` through the caller's hooks, or the Rust allocator when
/// none were supplied (C falls back to stdlib in exactly the same place).
///
/// # Safety
/// `mem`'s function pointers, if non-null, have the signatures declared in
/// `lz4frame.h:742-749`.
unsafe fn owned_new<T>(mem: LZ4F_CustomMem, value: T) -> *mut Owned<T> {
    let size = core::mem::size_of::<Owned<T>>();
    let block: *mut c_void = if !mem.customCalloc.is_null() {
        let f: AllocFn = unsafe { core::mem::transmute(mem.customCalloc) };
        unsafe { f(mem.opaqueState, size) }
    } else if !mem.customAlloc.is_null() {
        let f: AllocFn = unsafe { core::mem::transmute(mem.customAlloc) };
        unsafe { f(mem.opaqueState, size) }
    } else {
        // No hooks: a plain Box, whose pointer we then treat the same way.
        let b = Box::new(Owned {
            block: core::ptr::null_mut(),
            size,
            mem,
            value,
        });
        let raw = Box::into_raw(b);
        unsafe { (*raw).block = raw as *mut c_void };
        return raw;
    };
    if block.is_null() {
        return core::ptr::null_mut();
    }
    // The hook returned raw bytes; `Owned<T>` is not yet initialised there.
    let raw = block as *mut Owned<T>;
    unsafe {
        raw.write(Owned {
            block,
            size,
            mem,
            value,
        });
    }
    raw
}

/// Release an `Owned<T>` through whichever route allocated it.
///
/// # Safety
/// `raw` came from `owned_new` and is not used again.
unsafe fn owned_free<T>(raw: *mut Owned<T>) {
    if raw.is_null() {
        return;
    }
    let mem = unsafe { (*raw).mem };
    let block = unsafe { (*raw).block };
    if mem.customFree.is_null() && mem.customAlloc.is_null() && mem.customCalloc.is_null() {
        drop(unsafe { Box::from_raw(raw) });
        return;
    }
    // Drop the Rust value in place, then hand the bytes back to the caller.
    unsafe { core::ptr::drop_in_place(&mut (*raw).value) };
    if !mem.customFree.is_null() {
        let f: FreeFn = unsafe { core::mem::transmute(mem.customFree) };
        unsafe { f(mem.opaqueState, block) };
    }
}

/// The zero `LZ4F_CustomMem` — C's `LZ4F_defaultCMem` (lz4frame.h:755), which
/// means "use stdlib".
fn default_cmem() -> LZ4F_CustomMem {
    LZ4F_CustomMem {
        customAlloc: core::ptr::null_mut(),
        customCalloc: core::ptr::null_mut(),
        customFree: core::ptr::null_mut(),
        opaqueState: core::ptr::null_mut(),
    }
}

/// Turn a `Result` into the `LZ4F_*` return convention.
#[inline]
fn f_result(r: frame::Res<usize>) -> usize {
    match r {
        Ok(n) => n,
        Err(e) => e.to_code(),
    }
}

/// Read `LZ4F_preferences_t` into the plain-data mirror. `None` maps to C's
/// "NULL means all defaults".
///
/// # Safety
/// `p` is either null or a valid `LZ4F_preferences_t`.
unsafe fn read_prefs(p: *const LZ4F_preferences_t) -> Option<Preferences> {
    if p.is_null() {
        return None;
    }
    let c = unsafe { &*p };
    Some(Preferences {
        frame_info: FrameInfo {
            block_size_id: c.frameInfo.blockSizeID,
            block_mode: c.frameInfo.blockMode,
            content_checksum: c.frameInfo.contentChecksumFlag != 0,
            frame_type: c.frameInfo.frameType,
            content_size: c.frameInfo.contentSize as u64,
            dict_id: c.frameInfo.dictID as u32,
            block_checksum: c.frameInfo.blockChecksumFlag != 0,
        },
        compression_level: c.compressionLevel,
        auto_flush: c.autoFlush != 0,
        favor_dec_speed: c.favorDecSpeed != 0,
    })
}

/// Write the plain-data mirror back into a caller-provided `LZ4F_frameInfo_t`.
///
/// # Safety
/// `out` is a valid, writable `LZ4F_frameInfo_t`.
unsafe fn write_frame_info(out: *mut LZ4F_frameInfo_t, fi: &FrameInfo) {
    unsafe {
        (*out).blockSizeID = fi.block_size_id;
        (*out).blockMode = fi.block_mode;
        (*out).contentChecksumFlag = c_int::from(fi.content_checksum);
        (*out).frameType = fi.frame_type;
        (*out).contentSize = fi.content_size as c_ulonglong;
        (*out).dictID = fi.dict_id as c_uint;
        (*out).blockChecksumFlag = c_int::from(fi.block_checksum);
    }
}

/// A `*mut c_void` + length as a slice, tolerating C's null-with-zero-length.
///
/// # Safety
/// `p` is either null or valid for `len` bytes.
#[inline]
unsafe fn opt_slice<'a>(p: *const c_void, len: usize) -> &'a [u8] {
    if p.is_null() || len == 0 {
        &[]
    } else {
        unsafe { slice::from_raw_parts(p as *const u8, len) }
    }
}

/// # Safety
/// `p` is either null or valid and writable for `len` bytes.
#[inline]
unsafe fn opt_slice_mut<'a>(p: *mut c_void, len: usize) -> &'a mut [u8] {
    if p.is_null() || len == 0 {
        &mut []
    } else {
        unsafe { slice::from_raw_parts_mut(p as *mut u8, len) }
    }
}

/// from lib/lz4frame.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_cctx_size(cctx: *const LZ4F_cctx) -> usize {
    if cctx.is_null() {
        return 0;
    }
    // Exactly what the caller's allocator recorded. C adds `maxBufferSize`
    // because its working buffers also come from the hooks; ours are Rust Vecs
    // on the Rust heap, so counting them here would claim bytes the caller's
    // allocator never saw — frametest.c:1110 asserts the two totals are equal.
    let o = unsafe { &*(cctx as *const Owned<Cctx>) };
    o.size
}

/// from lib/lz4frame.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_compressBegin(
    cctx: *mut LZ4F_cctx,
    dstBuffer: *mut c_void,
    dstCapacity: usize,
    prefsPtr: *const LZ4F_preferences_t,
) -> usize {
    LZ4F_compressBegin_usingDict(cctx, dstBuffer, dstCapacity, core::ptr::null(), 0, prefsPtr)
}

/// from lib/lz4frame.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_compressBegin_usingCDict(
    cctx: *mut LZ4F_cctx,
    dstBuffer: *mut c_void,
    dstCapacity: usize,
    cdict: *const LZ4F_CDict,
    prefsPtr: *const LZ4F_preferences_t,
) -> usize {
    if cctx.is_null() {
        return frame::Error::ParameterNull.to_code();
    }
    let c = unsafe { &mut (*(cctx as *mut Owned<Cctx>)).value };
    let dst = unsafe { opt_slice_mut(dstBuffer, dstCapacity) };
    let prefs = unsafe { read_prefs(prefsPtr) };
    let cd = if cdict.is_null() {
        None
    } else {
        Some(unsafe { &*(cdict as *const CDict) })
    };
    f_result(c.begin(dst, None, cd, prefs.as_ref()))
}

/// from lib/lz4frame.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_compressBegin_usingDict(
    cctx: *mut LZ4F_cctx,
    dstBuffer: *mut c_void,
    dstCapacity: usize,
    dictBuffer: *const c_void,
    dictSize: usize,
    prefsPtr: *const LZ4F_preferences_t,
) -> usize {
    if cctx.is_null() {
        return frame::Error::ParameterNull.to_code();
    }
    let c = unsafe { &mut (*(cctx as *mut Owned<Cctx>)).value };
    let dst = unsafe { opt_slice_mut(dstBuffer, dstCapacity) };
    let prefs = unsafe { read_prefs(prefsPtr) };
    let dict = if dictBuffer.is_null() || dictSize == 0 {
        None
    } else {
        Some(unsafe { opt_slice(dictBuffer, dictSize) })
    };
    f_result(c.begin(dst, dict, None, prefs.as_ref()))
}

/// from lib/lz4frame.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_compressBound(
    srcSize: usize,
    prefsPtr: *const LZ4F_preferences_t,
) -> usize {
    let prefs = unsafe { read_prefs(prefsPtr) };
    frame::compress_bound(srcSize, prefs.as_ref())
}

/// from lib/lz4frame.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_compressEnd(
    cctx: *mut LZ4F_cctx,
    dstBuffer: *mut c_void,
    dstCapacity: usize,
    cOptPtr: *const LZ4F_compressOptions_t,
) -> usize {
    if cctx.is_null() {
        return frame::Error::ParameterNull.to_code();
    }
    let c = unsafe { &mut (*(cctx as *mut Owned<Cctx>)).value };
    let dst = unsafe { opt_slice_mut(dstBuffer, dstCapacity) };
    f_result(c.end(dst))
}

/// from lib/lz4frame.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_compressFrame(
    dstBuffer: *mut c_void,
    dstCapacity: usize,
    srcBuffer: *const c_void,
    srcSize: usize,
    preferencesPtr: *const LZ4F_preferences_t,
) -> usize {
    // C uses a stack context here to avoid an allocation (lz4frame.c:496); ours
    // is a short-lived Box, which is the same lifetime with a different home.
    let mut cctx = Cctx::new();
    let dst = unsafe { opt_slice_mut(dstBuffer, dstCapacity) };
    let src = unsafe { opt_slice(srcBuffer, srcSize) };
    let prefs = unsafe { read_prefs(preferencesPtr) };
    f_result(frame::compress_frame(
        &mut cctx,
        dst,
        src,
        None,
        prefs.as_ref(),
    ))
}

/// from lib/lz4frame.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_compressFrameBound(
    srcSize: usize,
    preferencesPtr: *const LZ4F_preferences_t,
) -> usize {
    let prefs = unsafe { read_prefs(preferencesPtr) };
    frame::compress_frame_bound(srcSize, prefs.as_ref())
}

/// from lib/lz4frame.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_compressFrame_usingCDict(
    cctx: *mut LZ4F_cctx,
    dst: *mut c_void,
    dstCapacity: usize,
    src: *const c_void,
    srcSize: usize,
    cdict: *const LZ4F_CDict,
    preferencesPtr: *const LZ4F_preferences_t,
) -> usize {
    if cctx.is_null() {
        return frame::Error::ParameterNull.to_code();
    }
    let c = unsafe { &mut (*(cctx as *mut Owned<Cctx>)).value };
    let dst = unsafe { opt_slice_mut(dst, dstCapacity) };
    let source = unsafe { opt_slice(src, srcSize) };
    let prefs = unsafe { read_prefs(preferencesPtr) };
    let cd = if cdict.is_null() {
        None
    } else {
        Some(unsafe { &*(cdict as *const CDict) })
    };
    f_result(frame::compress_frame(c, dst, source, cd, prefs.as_ref()))
}

/// from lib/lz4frame.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_compressUpdate(
    cctx: *mut LZ4F_cctx,
    dstBuffer: *mut c_void,
    dstCapacity: usize,
    srcBuffer: *const c_void,
    srcSize: usize,
    cOptPtr: *const LZ4F_compressOptions_t,
) -> usize {
    if cctx.is_null() {
        return frame::Error::ParameterNull.to_code();
    }
    let c = unsafe { &mut (*(cctx as *mut Owned<Cctx>)).value };
    let dst = unsafe { opt_slice_mut(dstBuffer, dstCapacity) };
    let src = unsafe { opt_slice(srcBuffer, srcSize) };
    f_result(c.update(dst, src, BlockCompressMode::Compressed))
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_compressionLevel_max() -> c_int {
    frame::LZ4HC_CLEVEL_MAX as c_int
}

/// from lib/lz4frame.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_createCDict(
    dictBuffer: *const c_void,
    dictSize: usize,
) -> *mut LZ4F_CDict {
    LZ4F_createCDict_advanced(
        LZ4F_CustomMem {
            customAlloc: core::ptr::null_mut(),
            customCalloc: core::ptr::null_mut(),
            customFree: core::ptr::null_mut(),
            opaqueState: core::ptr::null_mut(),
        },
        dictBuffer,
        dictSize,
    )
}

/// from lib/lz4frame.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_createCDict_advanced(
    customMem: LZ4F_CustomMem,
    dictBuffer: *const c_void,
    dictSize: usize,
) -> *mut LZ4F_CDict {
    if dictBuffer.is_null() {
        return core::ptr::null_mut();
    }
    let d = unsafe { opt_slice(dictBuffer, dictSize) };
    Box::into_raw(Box::new(CDict::new(d))) as *mut LZ4F_CDict
}

/// from lib/lz4frame.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_createCompressionContext(
    cctxPtr: *mut *mut LZ4F_cctx,
    version: c_uint,
) -> LZ4F_errorCode_t {
    if cctxPtr.is_null() {
        return frame::Error::ParameterNull.to_code();
    }
    let p = LZ4F_createCompressionContext_advanced(default_cmem(), version);
    unsafe { *cctxPtr = p };
    if p.is_null() {
        return frame::Error::AllocationFailed.to_code();
    }
    0
}

/// from lib/lz4frame.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_createCompressionContext_advanced(
    customMem: LZ4F_CustomMem,
    version: c_uint,
) -> *mut LZ4F_cctx {
    let mut c = Cctx::new();
    c.version = version as u32;
    unsafe { owned_new(customMem, c) as *mut LZ4F_cctx }
}

/// from lib/lz4frame.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_createDecompressionContext(
    dctxPtr: *mut *mut LZ4F_dctx,
    version: c_uint,
) -> LZ4F_errorCode_t {
    if dctxPtr.is_null() {
        return frame::Error::ParameterNull.to_code();
    }
    let p = LZ4F_createDecompressionContext_advanced(default_cmem(), version);
    unsafe { *dctxPtr = p };
    if p.is_null() {
        return frame::Error::AllocationFailed.to_code();
    }
    0
}

/// from lib/lz4frame.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_createDecompressionContext_advanced(
    customMem: LZ4F_CustomMem,
    version: c_uint,
) -> *mut LZ4F_dctx {
    let mut d = Dctx::new();
    d.version = version as u32;
    unsafe { owned_new(customMem, d) as *mut LZ4F_dctx }
}

/// from lib/lz4frame.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_dctx_size(dctx: *const LZ4F_dctx) -> usize {
    if dctx.is_null() {
        return 0;
    }
    // Same reasoning as `LZ4F_cctx_size`: report only hook-allocated bytes.
    let o = unsafe { &*(dctx as *const Owned<Dctx>) };
    o.size
}

/// from lib/lz4frame.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_decompress(
    dctx: *mut LZ4F_dctx,
    dstBuffer: *mut c_void,
    dstSizePtr: *mut usize,
    srcBuffer: *const c_void,
    srcSizePtr: *mut usize,
    dOptPtr: *const LZ4F_decompressOptions_t,
) -> usize {
    LZ4F_decompress_usingDict(
        dctx,
        dstBuffer,
        dstSizePtr,
        srcBuffer,
        srcSizePtr,
        core::ptr::null(),
        0,
        dOptPtr,
    )
}

/// from lib/lz4frame.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_decompress_usingDict(
    dctxPtr: *mut LZ4F_dctx,
    dstBuffer: *mut c_void,
    dstSizePtr: *mut usize,
    srcBuffer: *const c_void,
    srcSizePtr: *mut usize,
    dict: *const c_void,
    dictSize: usize,
    decompressOptionsPtr: *const LZ4F_decompressOptions_t,
) -> usize {
    if dctxPtr.is_null() || dstSizePtr.is_null() || srcSizePtr.is_null() {
        return frame::Error::ParameterNull.to_code();
    }
    let d = unsafe { &mut (*(dctxPtr as *mut Owned<Dctx>)).value };
    let dst_cap = unsafe { *dstSizePtr };
    let src_len = unsafe { *srcSizePtr };
    let dst = unsafe { opt_slice_mut(dstBuffer, dst_cap) };
    let src = unsafe { opt_slice(srcBuffer, src_len) };
    let dict = if dict.is_null() || dictSize == 0 {
        None
    } else {
        Some(unsafe { opt_slice(dict, dictSize) })
    };
    let skip = if decompressOptionsPtr.is_null() {
        false
    } else {
        unsafe { (*decompressOptionsPtr).skipChecksums != 0 }
    };

    // Both counts are reported even on failure, and C zeroes them first, so a
    // caller that ignores the error still sees a consistent pair.
    unsafe {
        *dstSizePtr = 0;
        *srcSizePtr = 0;
    }
    match frame::decompress(d, dst, src, dict, skip) {
        Ok(p) => {
            unsafe {
                *dstSizePtr = p.dst_written;
                *srcSizePtr = p.src_consumed;
            }
            p.hint
        }
        Err(e) => e.to_code(),
    }
}

/// from lib/lz4frame.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_flush(
    cctx: *mut LZ4F_cctx,
    dstBuffer: *mut c_void,
    dstCapacity: usize,
    cOptPtr: *const LZ4F_compressOptions_t,
) -> usize {
    if cctx.is_null() {
        return frame::Error::ParameterNull.to_code();
    }
    let c = unsafe { &mut (*(cctx as *mut Owned<Cctx>)).value };
    let dst = unsafe { opt_slice_mut(dstBuffer, dstCapacity) };
    f_result(c.flush(dst))
}

/// from lib/lz4frame.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_freeCDict(CDict: *mut LZ4F_CDict) {
    if !CDict.is_null() {
        drop(unsafe { Box::from_raw(CDict as *mut CDict) });
    }
}

/// from lib/lz4frame.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_freeCompressionContext(cctx: *mut LZ4F_cctx) -> LZ4F_errorCode_t {
    // Accepts NULL, like free().
    unsafe { owned_free(cctx as *mut Owned<Cctx>) };
    0
}

/// from lib/lz4frame.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_freeDecompressionContext(dctx: *mut LZ4F_dctx) -> LZ4F_errorCode_t {
    // The return value is the stage the context died in: 0 only when the frame
    // was decoded fully and correctly, which is what frametest asserts on.
    if dctx.is_null() {
        return 0;
    }
    let stage = unsafe { (*(dctx as *mut Owned<Dctx>)).value.stage } as usize;
    unsafe { owned_free(dctx as *mut Owned<Dctx>) };
    stage
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_getBlockSize(blockSizeID: LZ4F_blockSizeID_t) -> usize {
    f_result(frame::get_block_size(blockSizeID))
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_getErrorCode(functionResult: usize) -> LZ4F_errorCodes {
    frame::error_code(functionResult) as LZ4F_errorCodes
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_getErrorName(code: LZ4F_errorCode_t) -> *const c_char {
    // C returns a pointer into a static string table, valid for the life of the
    // program. Our statics are NUL-terminated for exactly this reason.
    let idx = frame::error_code(code);
    let s: &'static [u8] = if frame::is_error(code) && (idx as usize) < frame::ERROR_STRINGS.len() {
        frame::ERROR_STRINGS[idx as usize]
    } else {
        b"Unspecified error code\0"
    };
    s.as_ptr() as *const c_char
}

/// from lib/lz4frame.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_getFrameInfo(
    dctx: *mut LZ4F_dctx,
    frameInfoPtr: *mut LZ4F_frameInfo_t,
    srcBuffer: *const c_void,
    srcSizePtr: *mut usize,
) -> usize {
    if dctx.is_null() {
        return frame::Error::ParameterNull.to_code();
    }
    if frameInfoPtr.is_null() || srcSizePtr.is_null() {
        return frame::Error::ParameterNull.to_code();
    }
    let d = unsafe { &mut (*(dctx as *mut Owned<Dctx>)).value };
    let src_len = unsafe { *srcSizePtr };
    let src = unsafe { opt_slice(srcBuffer, src_len) };
    match frame::get_frame_info(d, src) {
        Ok((fi, consumed, hint)) => {
            unsafe {
                *srcSizePtr = consumed;
                write_frame_info(frameInfoPtr, &fi);
            }
            hint
        }
        Err(e) => {
            // On error C leaves dctx untouched and reports nothing consumed.
            unsafe { *srcSizePtr = 0 };
            e.to_code()
        }
    }
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_getVersion() -> c_uint {
    frame::LZ4F_VERSION as c_uint
}

/// from lib/lz4frame.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_headerSize(src: *const c_void, srcSize: usize) -> usize {
    if src.is_null() {
        return frame::Error::SrcPtrWrong.to_code();
    }
    let s = unsafe { opt_slice(src, srcSize) };
    f_result(frame::header_size(s))
}

/// from lib/lz4frame.h
#[no_mangle]
pub extern "C" fn LZ4F_isError(code: LZ4F_errorCode_t) -> c_uint {
    c_uint::from(frame::is_error(code))
}

// ===========================================================================
// File API (lib/lz4file.c)
// ===========================================================================
//
// This layer works on a `FILE*` the C caller owns and may already have read
// from, so the stream cannot be re-opened as a Rust `File` — duplicating the
// descriptor would desynchronise the file position. The stdio calls therefore
// live here, declared directly, and everything else is in `crate::file`.

extern "C" {
    fn fread(ptr: *mut c_void, size: usize, nmemb: usize, stream: *mut FILE) -> usize;
    fn fwrite(ptr: *const c_void, size: usize, nmemb: usize, stream: *mut FILE) -> usize;
    fn ferror(stream: *mut FILE) -> c_int;
}

/// `crate::file::Io` over the caller's `FILE*`.
struct CFile(*mut FILE);

impl crate::file::Io for CFile {
    fn read(&mut self, buf: &mut [u8]) -> usize {
        if buf.is_empty() {
            return 0;
        }
        unsafe { fread(buf.as_mut_ptr() as *mut c_void, 1, buf.len(), self.0) }
    }
    fn write(&mut self, buf: &[u8]) -> usize {
        if buf.is_empty() {
            return 0;
        }
        unsafe { fwrite(buf.as_ptr() as *const c_void, 1, buf.len(), self.0) }
    }
    fn error(&mut self) -> bool {
        unsafe { ferror(self.0) != 0 }
    }
}

/// The handles C holds: our state plus the stream it is bound to. C keeps the
/// `FILE*` inside its own struct too (lz4file.c:54, :207), so the pairing is
/// the original's, not an invention.
struct ReadHandle {
    state: crate::file::ReadFile,
    fp: *mut FILE,
}

struct WriteHandle {
    state: crate::file::WriteFile,
    fp: *mut FILE,
}

/// from lib/lz4file.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_read(
    lz4fRead: *mut LZ4_readFile_t,
    buf: *mut c_void,
    size: usize,
) -> usize {
    if lz4fRead.is_null() || buf.is_null() {
        return frame::Error::ParameterNull.to_code();
    }
    let h = unsafe { &mut *(lz4fRead as *mut ReadHandle) };
    let out = unsafe { slice::from_raw_parts_mut(buf as *mut u8, size) };
    let mut io = CFile(h.fp);
    match h.state.read(&mut io, out) {
        Ok(n) => n,
        Err(e) => e.to_code(),
    }
}

/// from lib/lz4file.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_readClose(lz4fRead: *mut LZ4_readFile_t) -> LZ4F_errorCode_t {
    if lz4fRead.is_null() {
        return frame::Error::ParameterNull.to_code();
    }
    drop(unsafe { Box::from_raw(lz4fRead as *mut ReadHandle) });
    0
}

/// from lib/lz4file.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_readOpen(
    lz4fRead: *mut *mut LZ4_readFile_t,
    fp: *mut FILE,
) -> LZ4F_errorCode_t {
    if fp.is_null() || lz4fRead.is_null() {
        return frame::Error::ParameterNull.to_code();
    }
    let mut io = CFile(fp);
    match crate::file::ReadFile::open(&mut io) {
        Ok(state) => {
            let h = Box::new(ReadHandle { state, fp });
            unsafe { *lz4fRead = Box::into_raw(h) as *mut LZ4_readFile_t };
            0
        }
        Err(e) => e.to_code(),
    }
}

/// from lib/lz4frame.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_resetDecompressionContext(dctx: *mut LZ4F_dctx) {
    if dctx.is_null() {
        return;
    }
    unsafe { &mut (*(dctx as *mut Owned<Dctx>)).value }.reset()
}

/// from lib/lz4frame.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_uncompressedUpdate(
    cctx: *mut LZ4F_cctx,
    dstBuffer: *mut c_void,
    dstCapacity: usize,
    srcBuffer: *const c_void,
    srcSize: usize,
    cOptPtr: *const LZ4F_compressOptions_t,
) -> usize {
    if cctx.is_null() {
        return frame::Error::ParameterNull.to_code();
    }
    let c = unsafe { &mut (*(cctx as *mut Owned<Cctx>)).value };
    let dst = unsafe { opt_slice_mut(dstBuffer, dstCapacity) };
    let src = unsafe { opt_slice(srcBuffer, srcSize) };
    f_result(c.update(dst, src, BlockCompressMode::Uncompressed))
}

/// from lib/lz4file.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_write(
    lz4fWrite: *mut LZ4_writeFile_t,
    buf: *const c_void,
    size: usize,
) -> usize {
    if lz4fWrite.is_null() || buf.is_null() {
        return frame::Error::ParameterNull.to_code();
    }
    let h = unsafe { &mut *(lz4fWrite as *mut WriteHandle) };
    let src = unsafe { slice::from_raw_parts(buf as *const u8, size) };
    let mut io = CFile(h.fp);
    match h.state.write(&mut io, src) {
        Ok(n) => n,
        Err(e) => e.to_code(),
    }
}

/// from lib/lz4file.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_writeClose(lz4fWrite: *mut LZ4_writeFile_t) -> LZ4F_errorCode_t {
    if lz4fWrite.is_null() {
        return frame::Error::ParameterNull.to_code();
    }
    // The state is freed either way, as C does: `freeWriteFileResources` runs
    // past the `cleanup` label on both paths.
    let mut h = unsafe { Box::from_raw(lz4fWrite as *mut WriteHandle) };
    let mut io = CFile(h.fp);
    match h.state.close(&mut io) {
        Ok(()) => 0,
        Err(e) => e.to_code(),
    }
}

/// from lib/lz4file.h
#[no_mangle]
pub unsafe extern "C" fn LZ4F_writeOpen(
    lz4fWrite: *mut *mut LZ4_writeFile_t,
    fp: *mut FILE,
    prefsPtr: *const LZ4F_preferences_t,
) -> LZ4F_errorCode_t {
    if fp.is_null() || lz4fWrite.is_null() {
        return frame::Error::ParameterNull.to_code();
    }
    let mut io = CFile(fp);
    let prefs = unsafe { read_prefs(prefsPtr) };
    match crate::file::WriteFile::open(&mut io, prefs.as_ref()) {
        Ok(state) => {
            let h = Box::new(WriteHandle { state, fp });
            unsafe { *lz4fWrite = Box::into_raw(h) as *mut LZ4_writeFile_t };
            0
        }
        Err(e) => e.to_code(),
    }
}

// ─── XXH helpers ─────────────────────────────────────────────────────────────
//
// The opaque storage types (XXH32_state_t, XXH64_state_t) are the same byte
// size and alignment as the internal Xxh*State structs. types.rs asserts the
// storage types against the C probe; the asserts below close the loop by
// pinning the internal structs to the storage types, so the pointer casts
// here are checked end-to-end at compile time.

use crate::xxh::{Xxh32State, Xxh64State};

const _: () = {
    assert!(core::mem::size_of::<Xxh32State>() == core::mem::size_of::<XXH32_state_t>());
    assert!(core::mem::align_of::<Xxh32State>() == core::mem::align_of::<XXH32_state_t>());
    assert!(core::mem::size_of::<Xxh64State>() == core::mem::size_of::<XXH64_state_t>());
    assert!(core::mem::align_of::<Xxh64State>() == core::mem::align_of::<XXH64_state_t>());
};

#[inline]
unsafe fn as_xxh32(p: *mut XXH32_state_t) -> &'static mut Xxh32State {
    unsafe { &mut *(p as *mut Xxh32State) }
}
#[inline]
unsafe fn as_xxh32_ref(p: *const XXH32_state_t) -> &'static Xxh32State {
    unsafe { &*(p as *const Xxh32State) }
}
#[inline]
unsafe fn as_xxh64(p: *mut XXH64_state_t) -> &'static mut Xxh64State {
    unsafe { &mut *(p as *mut Xxh64State) }
}
#[inline]
unsafe fn as_xxh64_ref(p: *const XXH64_state_t) -> &'static Xxh64State {
    unsafe { &*(p as *const Xxh64State) }
}

/// from lib/xxhash.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_XXH32(
    input: *const c_void,
    length: usize,
    seed: c_uint,
) -> XXH32_hash_t {
    let data = if input.is_null() {
        &[]
    } else {
        unsafe { slice::from_raw_parts(input as *const u8, length) }
    };
    crate::xxh::xxh32(data, seed)
}

/// from lib/xxhash.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_XXH32_canonicalFromHash(
    dst: *mut XXH32_canonical_t,
    hash: XXH32_hash_t,
) {
    unsafe {
        (*dst).digest = crate::xxh::xxh32_canonical_from_hash(hash);
    }
}

/// from lib/xxhash.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_XXH32_copyState(
    dst_state: *mut XXH32_state_t,
    src_state: *const XXH32_state_t,
) {
    unsafe {
        *as_xxh32(dst_state) = *as_xxh32_ref(src_state);
    }
}

/// from lib/xxhash.h — allocates; caller must free with LZ4_XXH32_freeState
#[no_mangle]
pub extern "C" fn LZ4_XXH32_createState() -> *mut XXH32_state_t {
    // Safety: Box::into_raw gives us a valid, non-null pointer.
    let b: Box<Xxh32State> = Box::new(Xxh32State {
        total_len_32: 0,
        large_len: 0,
        v1: 0,
        v2: 0,
        v3: 0,
        v4: 0,
        mem: [0; 16],
        memsize: 0,
        reserved: 0,
    });
    Box::into_raw(b) as *mut XXH32_state_t
}

/// from lib/xxhash.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_XXH32_digest(statePtr: *const XXH32_state_t) -> XXH32_hash_t {
    crate::xxh::xxh32_digest(unsafe { as_xxh32_ref(statePtr) })
}

/// from lib/xxhash.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_XXH32_freeState(statePtr: *mut XXH32_state_t) -> XXH_errorcode {
    if !statePtr.is_null() {
        unsafe {
            drop(Box::from_raw(statePtr as *mut Xxh32State));
        }
    }
    crate::types::XXH_OK
}

/// from lib/xxhash.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_XXH32_hashFromCanonical(
    src: *const XXH32_canonical_t,
) -> XXH32_hash_t {
    crate::xxh::xxh32_hash_from_canonical(unsafe { &(*src).digest })
}

/// from lib/xxhash.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_XXH32_reset(
    statePtr: *mut XXH32_state_t,
    seed: c_uint,
) -> XXH_errorcode {
    crate::xxh::xxh32_reset(unsafe { as_xxh32(statePtr) }, seed);
    crate::types::XXH_OK
}

/// from lib/xxhash.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_XXH32_update(
    statePtr: *mut XXH32_state_t,
    input: *const c_void,
    length: usize,
) -> XXH_errorcode {
    if input.is_null() {
        return crate::types::XXH_ERROR;
    }
    let data = unsafe { slice::from_raw_parts(input as *const u8, length) };
    crate::xxh::xxh32_update(unsafe { as_xxh32(statePtr) }, data);
    crate::types::XXH_OK
}

/// from lib/xxhash.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_XXH64(
    input: *const c_void,
    length: usize,
    seed: c_ulonglong,
) -> XXH64_hash_t {
    let data = if input.is_null() {
        &[]
    } else {
        unsafe { slice::from_raw_parts(input as *const u8, length) }
    };
    crate::xxh::xxh64(data, seed)
}

/// from lib/xxhash.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_XXH64_canonicalFromHash(
    dst: *mut XXH64_canonical_t,
    hash: XXH64_hash_t,
) {
    unsafe {
        (*dst).digest = crate::xxh::xxh64_canonical_from_hash(hash);
    }
}

/// from lib/xxhash.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_XXH64_copyState(
    dst_state: *mut XXH64_state_t,
    src_state: *const XXH64_state_t,
) {
    unsafe {
        *as_xxh64(dst_state) = *as_xxh64_ref(src_state);
    }
}

/// from lib/xxhash.h — allocates; caller must free with LZ4_XXH64_freeState
#[no_mangle]
pub extern "C" fn LZ4_XXH64_createState() -> *mut XXH64_state_t {
    let b: Box<Xxh64State> = Box::new(Xxh64State {
        total_len: 0,
        v1: 0,
        v2: 0,
        v3: 0,
        v4: 0,
        mem: [0; 32],
        memsize: 0,
        reserved: [0; 2],
    });
    Box::into_raw(b) as *mut XXH64_state_t
}

/// from lib/xxhash.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_XXH64_digest(statePtr: *const XXH64_state_t) -> XXH64_hash_t {
    crate::xxh::xxh64_digest(unsafe { as_xxh64_ref(statePtr) })
}

/// from lib/xxhash.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_XXH64_freeState(statePtr: *mut XXH64_state_t) -> XXH_errorcode {
    if !statePtr.is_null() {
        unsafe {
            drop(Box::from_raw(statePtr as *mut Xxh64State));
        }
    }
    crate::types::XXH_OK
}

/// from lib/xxhash.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_XXH64_hashFromCanonical(
    src: *const XXH64_canonical_t,
) -> XXH64_hash_t {
    crate::xxh::xxh64_hash_from_canonical(unsafe { &(*src).digest })
}

/// from lib/xxhash.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_XXH64_reset(
    statePtr: *mut XXH64_state_t,
    seed: c_ulonglong,
) -> XXH_errorcode {
    crate::xxh::xxh64_reset(unsafe { as_xxh64(statePtr) }, seed);
    crate::types::XXH_OK
}

/// from lib/xxhash.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_XXH64_update(
    statePtr: *mut XXH64_state_t,
    input: *const c_void,
    length: usize,
) -> XXH_errorcode {
    if input.is_null() {
        return crate::types::XXH_ERROR;
    }
    let data = unsafe { slice::from_raw_parts(input as *const u8, length) };
    crate::xxh::xxh64_update(unsafe { as_xxh64(statePtr) }, data);
    crate::types::XXH_OK
}

/// from lib/xxhash.h
#[no_mangle]
pub extern "C" fn LZ4_XXH_versionNumber() -> c_uint {
    crate::xxh::VERSION_NUMBER
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_attach_HC_dictionary(
    working_stream: *mut LZ4_streamHC_t,
    dictionary_stream: *const LZ4_streamHC_t,
) {
    unimplemented!("LZ4_attach_HC_dictionary")
}

/// from lib/lz4.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_attach_dictionary(
    workingStream: *mut LZ4_stream_t,
    dictionaryStream: *const LZ4_stream_t,
) {
    if workingStream.is_null() {
        return;
    }
    let dictionary_size = if dictionaryStream.is_null() {
        0
    } else {
        unsafe {
            core::ptr::addr_of!((*dictionaryStream.cast::<AbiStreamState>()).dict_size).read()
        }
    };
    let Some(mut working) = abi_stream_ptr(workingStream) else {
        return;
    };
    let working = unsafe { working.as_mut() };
    if dictionaryStream.is_null() {
        working.dict_ctx = 0;
        return;
    }
    if working.current_offset == 0 {
        working.current_offset = 64 * 1024;
    }
    working.dict_ctx = if dictionary_size == 0 {
        0
    } else {
        dictionaryStream as usize
    };
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_compress(src: *const c_char, dest: *mut c_char, srcSize: c_int) -> c_int {
    // lz4.c:2787 — deprecated alias.
    LZ4_compress_default(src, dest, srcSize, LZ4_compressBound(srcSize))
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_compressBound(inputSize: c_int) -> c_int {
    block::compress_bound(inputSize)
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compressHC(
    source: *const c_char,
    dest: *mut c_char,
    inputSize: c_int,
) -> c_int {
    unimplemented!("LZ4_compressHC")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compressHC2(
    source: *const c_char,
    dest: *mut c_char,
    inputSize: c_int,
    compressionLevel: c_int,
) -> c_int {
    unimplemented!("LZ4_compressHC2")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compressHC2_continue(
    LZ4HC_Data: *mut c_void,
    source: *const c_char,
    dest: *mut c_char,
    inputSize: c_int,
    compressionLevel: c_int,
) -> c_int {
    unimplemented!("LZ4_compressHC2_continue")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compressHC2_limitedOutput(
    source: *const c_char,
    dest: *mut c_char,
    inputSize: c_int,
    maxOutputSize: c_int,
    compressionLevel: c_int,
) -> c_int {
    unimplemented!("LZ4_compressHC2_limitedOutput")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compressHC2_limitedOutput_continue(
    LZ4HC_Data: *mut c_void,
    source: *const c_char,
    dest: *mut c_char,
    inputSize: c_int,
    maxOutputSize: c_int,
    compressionLevel: c_int,
) -> c_int {
    unimplemented!("LZ4_compressHC2_limitedOutput_continue")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compressHC2_limitedOutput_withStateHC(
    state: *mut c_void,
    source: *const c_char,
    dest: *mut c_char,
    inputSize: c_int,
    maxOutputSize: c_int,
    compressionLevel: c_int,
) -> c_int {
    unimplemented!("LZ4_compressHC2_limitedOutput_withStateHC")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compressHC2_withStateHC(
    state: *mut c_void,
    source: *const c_char,
    dest: *mut c_char,
    inputSize: c_int,
    compressionLevel: c_int,
) -> c_int {
    unimplemented!("LZ4_compressHC2_withStateHC")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compressHC_continue(
    LZ4_streamHCPtr: *mut LZ4_streamHC_t,
    source: *const c_char,
    dest: *mut c_char,
    inputSize: c_int,
) -> c_int {
    unimplemented!("LZ4_compressHC_continue")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compressHC_limitedOutput(
    source: *const c_char,
    dest: *mut c_char,
    inputSize: c_int,
    maxOutputSize: c_int,
) -> c_int {
    unimplemented!("LZ4_compressHC_limitedOutput")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compressHC_limitedOutput_continue(
    LZ4_streamHCPtr: *mut LZ4_streamHC_t,
    source: *const c_char,
    dest: *mut c_char,
    inputSize: c_int,
    maxOutputSize: c_int,
) -> c_int {
    unimplemented!("LZ4_compressHC_limitedOutput_continue")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compressHC_limitedOutput_withStateHC(
    state: *mut c_void,
    source: *const c_char,
    dest: *mut c_char,
    inputSize: c_int,
    maxOutputSize: c_int,
) -> c_int {
    unimplemented!("LZ4_compressHC_limitedOutput_withStateHC")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compressHC_withStateHC(
    state: *mut c_void,
    source: *const c_char,
    dest: *mut c_char,
    inputSize: c_int,
) -> c_int {
    unimplemented!("LZ4_compressHC_withStateHC")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compress_HC(
    src: *const c_char,
    dst: *mut c_char,
    srcSize: c_int,
    dstCapacity: c_int,
    compressionLevel: c_int,
) -> c_int {
    unimplemented!("LZ4_compress_HC")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compress_HC_continue(
    streamHCPtr: *mut LZ4_streamHC_t,
    src: *const c_char,
    dst: *mut c_char,
    srcSize: c_int,
    maxDstSize: c_int,
) -> c_int {
    unimplemented!("LZ4_compress_HC_continue")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compress_HC_continue_destSize(
    LZ4_streamHCPtr: *mut LZ4_streamHC_t,
    src: *const c_char,
    dst: *mut c_char,
    srcSizePtr: *mut c_int,
    targetDstSize: c_int,
) -> c_int {
    unimplemented!("LZ4_compress_HC_continue_destSize")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compress_HC_destSize(
    stateHC: *mut c_void,
    src: *const c_char,
    dst: *mut c_char,
    srcSizePtr: *mut c_int,
    targetDstSize: c_int,
    compressionLevel: c_int,
) -> c_int {
    unimplemented!("LZ4_compress_HC_destSize")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compress_HC_extStateHC(
    stateHC: *mut c_void,
    src: *const c_char,
    dst: *mut c_char,
    srcSize: c_int,
    maxDstSize: c_int,
    compressionLevel: c_int,
) -> c_int {
    unimplemented!("LZ4_compress_HC_extStateHC")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_compress_HC_extStateHC_fastReset(
    state: *mut c_void,
    src: *const c_char,
    dst: *mut c_char,
    srcSize: c_int,
    dstCapacity: c_int,
    compressionLevel: c_int,
) -> c_int {
    unimplemented!("LZ4_compress_HC_extStateHC_fastReset")
}

/// from lib/lz4.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_compress_continue(
    LZ4_streamPtr: *mut LZ4_stream_t,
    source: *const c_char,
    dest: *mut c_char,
    inputSize: c_int,
) -> c_int {
    unsafe {
        compress_continue_impl(
            LZ4_streamPtr,
            source,
            dest,
            inputSize,
            LZ4_compressBound(inputSize),
            1,
            false,
        )
    }
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_compress_default(
    src: *const c_char,
    dst: *mut c_char,
    srcSize: c_int,
    dstCapacity: c_int,
) -> c_int {
    // lz4.c:1481 — acceleration 1.
    LZ4_compress_fast(src, dst, srcSize, dstCapacity, 1)
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_compress_destSize(
    src: *const c_char,
    dst: *mut c_char,
    srcSizePtr: *mut c_int,
    targetDstSize: c_int,
) -> c_int {
    if srcSizePtr.is_null() || targetDstSize < 0 {
        return 0;
    }
    let src_size = unsafe { *srcSizePtr };
    if src_size < 0 || (src_size != 0 && src.is_null()) || dst.is_null() {
        return 0;
    }
    unsafe {
        with_buffers(
            src,
            src_size as usize,
            dst,
            targetDstSize as usize,
            |buf, range, input| match block::compress_dest_size(buf, range, input, 1) {
                Ok((written, consumed)) => {
                    *srcSizePtr = consumed as c_int;
                    written as c_int
                }
                Err(_) => 0,
            },
        )
    }
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_compress_destSize_extState(
    state: *mut c_void,
    src: *const c_char,
    dst: *mut c_char,
    srcSizePtr: *mut c_int,
    targetDstSize: c_int,
    acceleration: c_int,
) -> c_int {
    if state.is_null()
        || state as usize % core::mem::align_of::<AbiStreamState>() != 0
        || srcSizePtr.is_null()
    {
        return 0;
    }
    unsafe { (&mut *state.cast::<AbiStreamState>()).reset() };
    let result = if acceleration == 1 {
        LZ4_compress_destSize(src, dst, srcSizePtr, targetDstSize)
    } else {
        let src_size = unsafe { *srcSizePtr };
        if src_size < 0 || targetDstSize < 0 || (src_size != 0 && src.is_null()) || dst.is_null() {
            0
        } else {
            unsafe {
                with_buffers(
                    src,
                    src_size as usize,
                    dst,
                    targetDstSize as usize,
                    |buf, range, input| match block::compress_dest_size(
                        buf,
                        range,
                        input,
                        acceleration.max(1),
                    ) {
                        Ok((written, consumed)) => {
                            *srcSizePtr = consumed as c_int;
                            written as c_int
                        }
                        Err(_) => 0,
                    },
                )
            }
        }
    };
    unsafe { (&mut *state.cast::<AbiStreamState>()).reset() };
    result
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_compress_fast(
    src: *const c_char,
    dst: *mut c_char,
    srcSize: c_int,
    dstCapacity: c_int,
    acceleration: c_int,
) -> c_int {
    // A negative srcSize fails C's unsigned `> LZ4_MAX_INPUT_SIZE` test and
    // returns 0 (lz4.c:1369); the compress family never returns negative.
    if srcSize < 0 || (srcSize as u32) > block::LZ4_MAX_INPUT_SIZE || dstCapacity < 0 {
        return 0;
    }
    unsafe {
        with_buffers(
            src,
            srcSize as usize,
            dst,
            dstCapacity as usize,
            |buf, d, input| match block::compress_fast(buf, d, input, acceleration) {
                Ok(n) => n as c_int,
                Err(_) => 0,
            },
        )
    }
}

/// from lib/lz4.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_compress_fast_continue(
    streamPtr: *mut LZ4_stream_t,
    src: *const c_char,
    dst: *mut c_char,
    srcSize: c_int,
    dstCapacity: c_int,
    acceleration: c_int,
) -> c_int {
    unsafe {
        compress_continue_impl(
            streamPtr,
            src,
            dst,
            srcSize,
            dstCapacity,
            acceleration,
            false,
        )
    }
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_compress_fast_extState(
    state: *mut c_void,
    src: *const c_char,
    dst: *mut c_char,
    srcSize: c_int,
    dstCapacity: c_int,
    acceleration: c_int,
) -> c_int {
    unsafe { compress_ext_state_impl(state, src, dst, srcSize, dstCapacity, acceleration, false) }
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_compress_fast_extState_fastReset(
    state: *mut c_void,
    src: *const c_char,
    dst: *mut c_char,
    srcSize: c_int,
    dstCapacity: c_int,
    acceleration: c_int,
) -> c_int {
    unsafe { compress_ext_state_impl(state, src, dst, srcSize, dstCapacity, acceleration, true) }
}

/// from lib/lz4.c
#[no_mangle]
pub unsafe extern "C" fn LZ4_compress_forceExtDict(
    LZ4_dict: *mut LZ4_stream_t,
    source: *const c_char,
    dest: *mut c_char,
    srcSize: c_int,
) -> c_int {
    unsafe {
        compress_continue_impl(
            LZ4_dict,
            source,
            dest,
            srcSize,
            LZ4_compressBound(srcSize),
            1,
            true,
        )
    }
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_compress_limitedOutput(
    src: *const c_char,
    dest: *mut c_char,
    srcSize: c_int,
    maxOutputSize: c_int,
) -> c_int {
    // lz4.c:2783 — deprecated alias.
    LZ4_compress_default(src, dest, srcSize, maxOutputSize)
}

/// from lib/lz4.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_compress_limitedOutput_continue(
    LZ4_streamPtr: *mut LZ4_stream_t,
    source: *const c_char,
    dest: *mut c_char,
    inputSize: c_int,
    maxOutputSize: c_int,
) -> c_int {
    unsafe { LZ4_compress_fast_continue(LZ4_streamPtr, source, dest, inputSize, maxOutputSize, 1) }
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_compress_limitedOutput_withState(
    state: *mut c_void,
    source: *const c_char,
    dest: *mut c_char,
    inputSize: c_int,
    maxOutputSize: c_int,
) -> c_int {
    LZ4_compress_fast_extState(state, source, dest, inputSize, maxOutputSize, 1)
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_compress_withState(
    state: *mut c_void,
    source: *const c_char,
    dest: *mut c_char,
    inputSize: c_int,
) -> c_int {
    LZ4_compress_fast_extState(
        state,
        source,
        dest,
        inputSize,
        LZ4_compressBound(inputSize),
        1,
    )
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_create(inputBuffer: *mut c_char) -> *mut c_void {
    LZ4_createStream().cast()
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_createHC(inputBuffer: *const c_char) -> *mut c_void {
    unimplemented!("LZ4_createHC")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_createStream() -> *mut LZ4_stream_t {
    unsafe { std::alloc::alloc_zeroed(std::alloc::Layout::new::<AbiStreamState>()) }.cast()
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_createStreamDecode() -> *mut LZ4_streamDecode_t {
    unsafe { std::alloc::alloc_zeroed(std::alloc::Layout::new::<AbiDecodeState>()) }.cast()
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_createStreamHC() -> *mut LZ4_streamHC_t {
    unimplemented!("LZ4_createStreamHC")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_decoderRingBufferSize(maxBlockSize: c_int) -> c_int {
    if !(0..=0x7e00_0000).contains(&maxBlockSize) {
        0
    } else {
        maxBlockSize.max(16) + 65_536 + 14
    }
}

/// from lib/lz4.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_decompress_fast(
    src: *const c_char,
    dst: *mut c_char,
    originalSize: c_int,
) -> c_int {
    unsafe { decompress_fast_impl(src, dst, originalSize, 0, 0, 0, 0) }
}

/// from lib/lz4.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_decompress_fast_continue(
    LZ4_streamDecode: *mut LZ4_streamDecode_t,
    src: *const c_char,
    dst: *mut c_char,
    originalSize: c_int,
) -> c_int {
    unsafe { decompress_fast_continue_impl(LZ4_streamDecode, src, dst, originalSize) }
}

/// from lib/lz4.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_decompress_fast_usingDict(
    src: *const c_char,
    dst: *mut c_char,
    originalSize: c_int,
    dictStart: *const c_char,
    dictSize: c_int,
) -> c_int {
    if dictSize < 0 || (dictSize != 0 && dictStart.is_null()) {
        return -1;
    }
    if dictSize == 0 || (dictStart as usize).checked_add(dictSize as usize) == Some(dst as usize) {
        unsafe {
            decompress_fast_impl(
                src,
                dst,
                originalSize,
                0,
                0,
                dictStart as usize,
                dictSize as usize,
            )
        }
    } else {
        unsafe {
            decompress_fast_impl(
                src,
                dst,
                originalSize,
                dictStart as usize,
                dictSize as usize,
                0,
                0,
            )
        }
    }
}

/// from lib/lz4.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_decompress_fast_withPrefix64k(
    src: *const c_char,
    dst: *mut c_char,
    originalSize: c_int,
) -> c_int {
    if dst.is_null() {
        return -1;
    }
    unsafe {
        decompress_fast_impl(
            src,
            dst,
            originalSize,
            0,
            0,
            dst.cast::<u8>().sub(64 * 1024) as usize,
            64 * 1024,
        )
    }
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_decompress_safe(
    src: *const c_char,
    dst: *mut c_char,
    compressedSize: c_int,
    dstCapacity: c_int,
) -> c_int {
    // lz4.c:2035 — `src == NULL` or a negative output size is a flat -1,
    // before any position-encoded error can arise.
    if src.is_null() || dstCapacity < 0 || compressedSize < 0 {
        return -1;
    }
    unsafe {
        with_buffers(
            src,
            compressedSize as usize,
            dst,
            dstCapacity as usize,
            |buf, d, input| decode_result(block::decompress_generic(buf, d, input, false, 0)),
        )
    }
}

/// from lib/lz4.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_decompress_safe_continue(
    LZ4_streamDecode: *mut LZ4_streamDecode_t,
    src: *const c_char,
    dst: *mut c_char,
    srcSize: c_int,
    dstCapacity: c_int,
) -> c_int {
    unsafe { decompress_safe_continue_impl(LZ4_streamDecode, src, dst, srcSize, dstCapacity) }
}

/// from lib/lz4.c
#[no_mangle]
pub unsafe extern "C" fn LZ4_decompress_safe_forceExtDict(
    source: *const c_char,
    dest: *mut c_char,
    compressedSize: c_int,
    maxOutputSize: c_int,
    dictStart: *const c_void,
    dictSize: usize,
) -> c_int {
    if dictSize > isize::MAX as usize {
        return -1;
    }
    unsafe {
        decompress_safe_impl(
            source,
            dest,
            compressedSize,
            maxOutputSize,
            Some((dictStart.cast(), dictSize)),
            true,
            false,
        )
    }
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_decompress_safe_partial(
    src: *const c_char,
    dst: *mut c_char,
    srcSize: c_int,
    targetOutputSize: c_int,
    dstCapacity: c_int,
) -> c_int {
    // lz4.c:2480 takes MIN(targetOutputSize, dstCapacity) as the output size,
    // so a negative target reaches the `outputSize < 0` check and yields -1.
    if src.is_null() || dstCapacity < 0 || targetOutputSize < 0 || srcSize < 0 {
        return -1;
    }
    unsafe {
        with_buffers(
            src,
            srcSize as usize,
            dst,
            dstCapacity as usize,
            |buf, d, input| {
                decode_result(block::decompress_generic(
                    buf,
                    d,
                    input,
                    true,
                    targetOutputSize as usize,
                ))
            },
        )
    }
}

/// from lib/lz4.c
#[no_mangle]
pub unsafe extern "C" fn LZ4_decompress_safe_partial_forceExtDict(
    source: *const c_char,
    dest: *mut c_char,
    compressedSize: c_int,
    targetOutputSize: c_int,
    dstCapacity: c_int,
    dictStart: *const c_void,
    dictSize: usize,
) -> c_int {
    if dictSize > isize::MAX as usize {
        return -1;
    }
    unsafe {
        decompress_safe_impl(
            source,
            dest,
            compressedSize,
            targetOutputSize.min(dstCapacity),
            Some((dictStart.cast(), dictSize)),
            true,
            true,
        )
    }
}

/// from lib/lz4.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_decompress_safe_partial_usingDict(
    src: *const c_char,
    dst: *mut c_char,
    compressedSize: c_int,
    targetOutputSize: c_int,
    maxOutputSize: c_int,
    dictStart: *const c_char,
    dictSize: c_int,
) -> c_int {
    if dictSize < 0 {
        return -1;
    }
    let dictionary = (dictSize != 0).then_some((dictStart, dictSize as usize));
    let external =
        dictSize != 0 && (dictStart as usize).checked_add(dictSize as usize) != Some(dst as usize);
    unsafe {
        decompress_safe_impl(
            src,
            dst,
            compressedSize,
            targetOutputSize.min(maxOutputSize),
            dictionary,
            external,
            true,
        )
    }
}

/// from lib/lz4.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_decompress_safe_usingDict(
    src: *const c_char,
    dst: *mut c_char,
    srcSize: c_int,
    dstCapacity: c_int,
    dictStart: *const c_char,
    dictSize: c_int,
) -> c_int {
    if dictSize < 0 {
        return -1;
    }
    let dictionary = (dictSize != 0).then_some((dictStart, dictSize as usize));
    let external =
        dictSize != 0 && (dictStart as usize).checked_add(dictSize as usize) != Some(dst as usize);
    unsafe { decompress_safe_impl(src, dst, srcSize, dstCapacity, dictionary, external, false) }
}

/// from lib/lz4.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_decompress_safe_withPrefix64k(
    src: *const c_char,
    dst: *mut c_char,
    compressedSize: c_int,
    maxDstSize: c_int,
) -> c_int {
    if dst.is_null() {
        return -1;
    }
    unsafe {
        decompress_safe_impl(
            src,
            dst,
            compressedSize,
            maxDstSize,
            Some((dst.cast::<u8>().sub(64 * 1024).cast(), 64 * 1024)),
            false,
            false,
        )
    }
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_favorDecompressionSpeed(LZ4_streamHCPtr: *mut LZ4_streamHC_t, favor: c_int) {
    unimplemented!("LZ4_favorDecompressionSpeed")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_freeHC(LZ4HC_Data: *mut c_void) -> c_int {
    unimplemented!("LZ4_freeHC")
}

/// from lib/lz4.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_freeStream(streamPtr: *mut LZ4_stream_t) -> c_int {
    if !streamPtr.is_null() {
        unsafe {
            std::alloc::dealloc(
                streamPtr.cast(),
                std::alloc::Layout::new::<AbiStreamState>(),
            )
        };
    }
    0
}

/// from lib/lz4.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_freeStreamDecode(LZ4_stream: *mut LZ4_streamDecode_t) -> c_int {
    if !LZ4_stream.is_null() {
        unsafe {
            std::alloc::dealloc(
                LZ4_stream.cast(),
                std::alloc::Layout::new::<AbiDecodeState>(),
            )
        };
    }
    0
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_freeStreamHC(streamHCPtr: *mut LZ4_streamHC_t) -> c_int {
    unimplemented!("LZ4_freeStreamHC")
}

/// from lib/lz4.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_initStream(
    stateBuffer: *mut c_void,
    size: usize,
) -> *mut LZ4_stream_t {
    if stateBuffer.is_null()
        || size < core::mem::size_of::<LZ4_stream_t>()
        || stateBuffer as usize % core::mem::align_of::<LZ4_stream_t>() != 0
    {
        return core::ptr::null_mut();
    }
    unsafe { (&mut *stateBuffer.cast::<AbiStreamState>()).reset() };
    stateBuffer.cast()
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_initStreamHC(buffer: *mut c_void, size: usize) -> *mut LZ4_streamHC_t {
    unimplemented!("LZ4_initStreamHC")
}

/// from lib/lz4.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_loadDict(
    streamPtr: *mut LZ4_stream_t,
    dictionary: *const c_char,
    dictSize: c_int,
) -> c_int {
    unsafe { load_dict_impl(streamPtr, dictionary, dictSize, false) }
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_loadDictHC(
    streamHCPtr: *mut LZ4_streamHC_t,
    dictionary: *const c_char,
    dictSize: c_int,
) -> c_int {
    unimplemented!("LZ4_loadDictHC")
}

/// from lib/lz4.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_loadDictSlow(
    streamPtr: *mut LZ4_stream_t,
    dictionary: *const c_char,
    dictSize: c_int,
) -> c_int {
    unsafe { load_dict_impl(streamPtr, dictionary, dictSize, true) }
}

/// from lib/lz4.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_resetStream(streamPtr: *mut LZ4_stream_t) {
    if let Some(mut state) = abi_stream_ptr(streamPtr) {
        unsafe { state.as_mut() }.reset();
    }
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_resetStreamHC(streamHCPtr: *mut LZ4_streamHC_t, compressionLevel: c_int) {
    unimplemented!("LZ4_resetStreamHC")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_resetStreamHC_fast(
    streamHCPtr: *mut LZ4_streamHC_t,
    compressionLevel: c_int,
) {
    unimplemented!("LZ4_resetStreamHC_fast")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_resetStreamState(state: *mut c_void, inputBuffer: *mut c_char) -> c_int {
    if state.is_null() || state as usize % core::mem::align_of::<AbiStreamState>() != 0 {
        1
    } else {
        unsafe { (&mut *state.cast::<AbiStreamState>()).reset() };
        0
    }
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_resetStreamStateHC(state: *mut c_void, inputBuffer: *mut c_char) -> c_int {
    unimplemented!("LZ4_resetStreamStateHC")
}

/// from lib/lz4.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_resetStream_fast(streamPtr: *mut LZ4_stream_t) {
    if let Some(mut state) = abi_stream_ptr(streamPtr) {
        unsafe { state.as_mut() }.reset_fast();
    }
}

/// from lib/lz4.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_saveDict(
    streamPtr: *mut LZ4_stream_t,
    safeBuffer: *mut c_char,
    maxDictSize: c_int,
) -> c_int {
    let Some(mut state) = abi_stream_ptr(streamPtr) else {
        return 0;
    };
    let state = unsafe { state.as_mut() };
    let size = if maxDictSize < 0 {
        64 * 1024
    } else {
        (maxDictSize as usize).min(64 * 1024)
    }
    .min(state.dict_size as usize);
    if size != 0 {
        if safeBuffer.is_null() || state.dictionary == 0 {
            return 0;
        }
        let source = (state.dictionary + state.dict_size as usize - size) as *const u8;
        unsafe { core::ptr::copy(source, safeBuffer.cast(), size) };
    }
    state.dictionary = safeBuffer as usize;
    state.dict_size = size as u32;
    size as c_int
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_saveDictHC(
    streamHCPtr: *mut LZ4_streamHC_t,
    safeBuffer: *mut c_char,
    maxDictSize: c_int,
) -> c_int {
    unimplemented!("LZ4_saveDictHC")
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_setCompressionLevel(
    LZ4_streamHCPtr: *mut LZ4_streamHC_t,
    compressionLevel: c_int,
) {
    unimplemented!("LZ4_setCompressionLevel")
}

/// from lib/lz4.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_setStreamDecode(
    LZ4_streamDecode: *mut LZ4_streamDecode_t,
    dictionary: *const c_char,
    dictSize: c_int,
) -> c_int {
    let Some(mut state) = abi_decode_ptr(LZ4_streamDecode) else {
        return 0;
    };
    let state = unsafe { state.as_mut() };
    if dictSize < 0 || (dictSize != 0 && dictionary.is_null()) {
        return 0;
    }
    state.prefix_size = dictSize as usize;
    state.prefix_end = (dictionary as usize).saturating_add(dictSize as usize);
    state.external_dict = 0;
    state.ext_dict_size = 0;
    1
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_sizeofState() -> c_int {
    // lz4.c:761 — `sizeof(LZ4_stream_t)`, probed from the real header.
    LZ4_STREAM_SIZE as c_int
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_sizeofStateHC() -> c_int {
    unimplemented!("LZ4_sizeofStateHC")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_sizeofStreamState() -> c_int {
    LZ4_sizeofState()
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_sizeofStreamStateHC() -> c_int {
    unimplemented!("LZ4_sizeofStreamStateHC")
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_slideInputBuffer(state: *mut c_void) -> *mut c_char {
    if state.is_null() {
        core::ptr::null_mut()
    } else {
        unsafe { (*state.cast::<AbiStreamState>()).dictionary as *mut c_char }
    }
}

/// from lib/lz4hc.h
#[no_mangle]
pub extern "C" fn LZ4_slideInputBufferHC(LZ4HC_Data: *mut c_void) -> *mut c_char {
    unimplemented!("LZ4_slideInputBufferHC")
}

/// from lib/lz4.h
#[no_mangle]
pub unsafe extern "C" fn LZ4_uncompress(
    source: *const c_char,
    dest: *mut c_char,
    outputSize: c_int,
) -> c_int {
    unsafe { LZ4_decompress_fast(source, dest, outputSize) }
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_uncompress_unknownOutputSize(
    source: *const c_char,
    dest: *mut c_char,
    isize: c_int,
    maxOutputSize: c_int,
) -> c_int {
    // lz4.c:2818 — deprecated alias.
    LZ4_decompress_safe(source, dest, isize, maxOutputSize)
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_versionNumber() -> c_int {
    crate::VERSION_NUMBER
}

/// from lib/lz4.h
#[no_mangle]
pub extern "C" fn LZ4_versionString() -> *const c_char {
    // The pointee is a `&'static [u8]`, so this address stays valid for the
    // life of the program -- matching C, which returns a string literal the
    // caller must not free. No `unsafe` needed: we hand out an address, we
    // never dereference one.
    crate::VERSION_STRING.as_ptr() as *const c_char
}
