//! A Rust port of the LZ4 compression library, ABI-compatible with liblz4.
//!
//! Layout of the crate:
//!
//! * `types`  — C-compatible struct/typedef definitions (the ABI boundary).
//! * `ffi`    — one `extern "C"` entry point per symbol the original
//!              `liblz4.a` exports. Generated by `port/tools/gen_ffi.py`.
//!              This is the only layer allowed to touch raw pointers.
//! * `block`, `hc`, `frame`, `file`, `xxh` — the actual implementation, in
//!              safe Rust operating on slices. Each of these modules sets
//!              `#![forbid(unsafe_code)]`, so the unsafe surface of the whole
//!              port is confined to `ffi` and is measurable for the write-up.
//!
//! Build produces `liblz4_rs.a`, which the *unmodified* original C test suite
//! links in place of the C objects. See DECISIONS.md.

#![allow(non_camel_case_types, non_snake_case)]

pub mod types;

pub mod block;
pub mod file;
pub mod frame;
pub mod hc;
pub mod xxh;

pub mod ffi;

/// LZ4 version this port targets, mirrored from the C headers at build time.
pub const VERSION_NUMBER: i32 = types::LZ4_VERSION_NUMBER_PROBED;
